In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.io as pio
import seaborn as sns
import numpy as np
pd.set_option('display.max_columns', 700)

In [19]:
df_train = pd.read_csv('TRAIN (1).csv')
df_train['order_date'] = pd.to_datetime(df_train['order_date'], format = '%m/%d/%y')
df_train['evsd'] = pd.to_datetime(df_train['evsd'], format = '%m/%d/%y')
df_train['tag'] = 'train'

print(df_train.shape)
df_train.head()

(259287, 14)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train
2,1,JFK2,648,16750,11165,2022-09-30,2022-10-03,AFT Lite,6,6,6,1,2,train
3,1,JFK2,648,16750,27008,2022-10-14,2022-10-17,AFT Lite,6,6,6,2,2,train
4,1,JFK2,7,8748,33598,2022-11-15,2022-11-16,AFT Lite,8,8,8,1,1,train

In [20]:
# Create a new column that combines the values of the existing columns
df_train['unique_id'] = df_train.apply(lambda row: f"{row['warehouse_id']}_{row['d_id']}_{row['isbn_id']}_{row['order_id']}\
                           _{row['order_date']}_{row['evsd']}_{row['row_group_ind']}_{row['visibility']}", axis=1)

# Drop duplicates based on the new column
df_unique = df_train.drop_duplicates(subset=['unique_id'])

df_unique.shape, df_train.shape

((259287, 15), (259287, 15))

In [21]:
df_train.nunique()

region_id                  1
warehouse_id               1
d_id                      38
isbn_id                 9059
order_id                1414
order_date                79
evsd                      81
po_source_ind              2
quantity_ordered         205
quantity_submitted       205
quantity_received        231
row_group_ind              8
visibility                25
tag                        1
unique_id             259287
dtype: int64

In [22]:
df_test = pd.read_csv('Test.csv', encoding = 'latin1')
# df_test.columns = ['LOCATION', 'd_id', 'isbn_id', 'order_id_1', 'order_date', 'evsd',
#        'row_group_ind', 'visibility', 'quantity_ordered', 'quantity_submitted',
#        'quantity_received']
df_test['order_date'] = pd.to_datetime(df_test['order_date'], format = '%m/%d/%y')
df_test['evsd'] = pd.to_datetime(df_test['evsd'], format = '%m/%d/%y')
df_test['tag'] = 'test'
print(df_test.shape)
df_test.head()

(98309, 14)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag
0,1,JFK2,684,674,45573,2022-12-15,2022-12-19,AFT Lite,42,42,42,3,3,test
1,1,JFK2,1,19822,110331,2022-12-27,2022-12-30,AFT Lite,6,6,6,0,3,test
2,1,JFK2,509,19749,119943,2022-12-15,2022-12-17,AFT Lite,12,12,12,3,1,test
3,1,JFK2,584,19747,43091,2022-12-20,2022-12-23,AFT Lite,12,12,12,4,3,test
4,1,JFK2,540,20260,117854,2022-12-26,2023-01-04,AFT Lite,60,60,60,1,8,test

In [23]:
df_test['unique_id'] = df_test.apply(lambda row: f"{row['warehouse_id']}_{row['d_id']}_{row['isbn_id']}_{row['order_id']}\
                           _{row['order_date']}_{row['evsd']}_{row['row_group_ind']}_{row['visibility']}", axis=1)

# Drop duplicates based on the new column
df_test = df_test.drop_duplicates(subset=['unique_id'])

print(df_test.shape)
df_test.head()

(98309, 15)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id
0,1,JFK2,684,674,45573,2022-12-15,2022-12-19,AFT Lite,42,42,42,3,3,test,JFK2_684_674_45573 _...
1,1,JFK2,1,19822,110331,2022-12-27,2022-12-30,AFT Lite,6,6,6,0,3,test,JFK2_1_19822_110331 ...
2,1,JFK2,509,19749,119943,2022-12-15,2022-12-17,AFT Lite,12,12,12,3,1,test,JFK2_509_19749_119943 ...
3,1,JFK2,584,19747,43091,2022-12-20,2022-12-23,AFT Lite,12,12,12,4,3,test,JFK2_584_19747_43091 ...
4,1,JFK2,540,20260,117854,2022-12-26,2023-01-04,AFT Lite,60,60,60,1,8,test,JFK2_540_20260_117854 ...

In [24]:
df_test.nunique()

region_id                 1
warehouse_id              1
d_id                     32
isbn_id                6539
order_id                579
order_date               31
evsd                     40
po_source_ind             2
quantity_ordered        168
quantity_submitted      183
quantity_received       205
row_group_ind             8
visibility               17
tag                       1
unique_id             98309
dtype: int64

In [25]:
df_train['po_source_ind'].value_counts(dropna = False)

po_source_ind
AFT Lite    259172
AFT            115
Name: count, dtype: int64

In [26]:
df_test['po_source_ind'].value_counts(dropna = False)

po_source_ind
AFT Lite    98260
AFT            49
Name: count, dtype: int64

In [27]:
for col in ['d_id', 'isbn_id', 'order_id']:
  df_train[col] = df_train[col].astype(int).astype(str)
  df_test[col] = df_test[col].astype(int).astype(str)

print(df_train.shape)
display(df_train.head(2))

print(df_test.shape)
df_test.head(2)

(259287, 15)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train,JFK2_540_30718_67271 ...
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train,JFK2_540_30718_125389 ...

(98309, 15)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id
0,1,JFK2,684,674,45573,2022-12-15,2022-12-19,AFT Lite,42,42,42,3,3,test,JFK2_684_674_45573 _...
1,1,JFK2,1,19822,110331,2022-12-27,2022-12-30,AFT Lite,6,6,6,0,3,test,JFK2_1_19822_110331 ...

In [28]:
# Define a funtion to peform one hot encoding for the top 10 most frequent categories of Categorical Features
def one_hot_top10(df,feature,top10_categories):
    for category in top10_categories:
        df[feature+'_'+category]=np.where(df[feature]==category,1,0)

In [29]:
# How long does order usually take to deliver?
df_train['order_delivery_days'] = (df_train['evsd'] - df_train['order_date']).dt.days
df_test['order_delivery_days'] = (df_test['evsd'] - df_test['order_date']).dt.days

In [30]:
# """
# Create a dict for the top 10 most frequent categories of Categorical Features
# Call the function to perform one hot encoding on Categorical Features
# verify the train and test set after applying one hot encoding for the Categorical 
# """

# var_dict_train ={}

# for col in ['d_id', 'isbn_id']:
#   var_dict_train[col] = [x for x in df_train[col].value_counts().sort_values(ascending=False).head(10).index]


# display(var_dict_train)

In [31]:
# for key,val in var_dict_train.items():
#   one_hot_top10(df_train,key,val)

# for key,val in var_dict_train.items():
#   one_hot_top10(df_test,key,val)

# display(df_train.head())
# display(df_test.head())

In [32]:
df_train['po_source_ind_AFT_Lite'] = np.where(df_train['po_source_ind'] == 'AFT Lite', 1, 0)
df_test['po_source_ind_AFT_Lite'] = np.where(df_test['po_source_ind'] == 'AFT Lite', 1, 0)

In [33]:
df_train['row_group_ind'] = df_train['row_group_ind'].astype(str)
var_dict_train_ ={}

for col in ['row_group_ind', 'd_id']:
  var_dict_train_[col] = [x for x in df_train[col].value_counts().sort_values(ascending=False).index]


display(var_dict_train_)

{'row_group_ind': ['1', '2', '4', '5', '3', '6', '0', '7'],
 'd_id': ['509',
  '584',
  '540',
  '648',
  '7',
  '410',
  '1',
  '643',
  '684',
  '454',
  '110',
  '639',
  '652',
  '524',
  '174',
  '18',
  '136',
  '472',
  '393',
  '566',
  '763',
  '218',
  '343',
  '711',
  '13',
  '302',
  '373',
  '830',
  '79',
  '613',
  '440',
  '845',
  '127',
  '216',
  '746',
  '462',
  '210',
  '241']}

In [34]:
for key,val in var_dict_train_.items():
  one_hot_top10(df_train,key,val)

for key,val in var_dict_train_.items():
  one_hot_top10(df_test,key,val)

display(df_train.head())
display(df_test.head())

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,po_source_ind_AFT_Lite,row_group_ind_1,row_group_ind_2,row_group_ind_4,row_group_ind_5,row_group_ind_3,row_group_ind_6,row_group_ind_0,row_group_ind_7,d_id_509,d_id_584,d_id_540,d_id_648,d_id_7,d_id_410,d_id_1,d_id_643,d_id_684,d_id_454,d_id_110,d_id_639,d_id_652,d_id_524,d_id_174,d_id_18,d_id_136,d_id_472,d_id_393,d_id_566,d_id_763,d_id_218,d_id_343,d_id_711,d_id_13,d_id_302,d_id_373,d_id_830,d_id_79,d_id_613,d_id_440,d_id_845,d_id_127,d_id_216,d_id_746,d_id_462,d_id_210,d_id_241
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train,JFK2_540_30718_67271 ...,12,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train,JFK2_540_30718_125389 ...,11,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,JFK2,648,16750,11165,2022-09-30,2022-10-03,AFT Lite,6,6,6,1,2,train,JFK2_648_16750_11165 ...,3,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,JFK2,648,16750,27008,2022-10-14,2022-10-17,AFT Lite,6,6,6,2,2,train,JFK2_648_16750_27008 ...,3,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,JFK2,7,8748,33598,2022-11-15,2022-11-16,AFT Lite,8,8,8,1,1,train,JFK2_7_8748_33598 _2...,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,po_source_ind_AFT_Lite,row_group_ind_1,row_group_ind_2,row_group_ind_4,row_group_ind_5,row_group_ind_3,row_group_ind_6,row_group_ind_0,row_group_ind_7,d_id_509,d_id_584,d_id_540,d_id_648,d_id_7,d_id_410,d_id_1,d_id_643,d_id_684,d_id_454,d_id_110,d_id_639,d_id_652,d_id_524,d_id_174,d_id_18,d_id_136,d_id_472,d_id_393,d_id_566,d_id_763,d_id_218,d_id_343,d_id_711,d_id_13,d_id_302,d_id_373,d_id_830,d_id_79,d_id_613,d_id_440,d_id_845,d_id_127,d_id_216,d_id_746,d_id_462,d_id_210,d_id_241
0,1,JFK2,684,674,45573,2022-12-15,2022-12-19,AFT Lite,42,42,42,3,3,test,JFK2_684_674_45573 _...,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,JFK2,1,19822,110331,2022-12-27,2022-12-30,AFT Lite,6,6,6,0,3,test,JFK2_1_19822_110331 ...,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1,JFK2,509,19749,119943,2022-12-15,2022-12-17,AFT Lite,12,12,12,3,1,test,JFK2_509_19749_119943 ...,2,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,JFK2,584,19747,43091,2022-12-20,2022-12-23,AFT Lite,12,12,12,4,3,test,JFK2_584_19747_43091 ...,3,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,JFK2,540,20260,117854,2022-12-26,2023-01-04,AFT Lite,60,60,60,1,8,test,JFK2_540_20260_117854 ...,9,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [43]:
isbn_vc = df_train['isbn_id'].value_counts(normalize = True).to_dict()

df_train['isbn_VC'] =  df_train['isbn_id'].map(isbn_vc)
df_test['isbn_VC'] =  df_test['isbn_id'].map(isbn_vc)

In [44]:
df_test.isnull().sum()

region_id                     0
warehouse_id                  0
d_id                          0
isbn_id                       0
order_id                      0
                           ...
delivered_month_sin           0
delivered_month_cos           0
delivered_dayofweek_sin       0
delivered_dayofweek_cos       0
isbn_VC                    2960
Length: 78, dtype: int64

In [45]:
df_test['isbn_VC'].fillna(0, inplace=True)

In [35]:

df_train['order_day'] = df_train['order_date'].dt.day
df_train['order_dayofweek'] = df_train['order_date'].dt.dayofweek
df_train['order_dayofyear'] = df_train['order_date'].dt.dayofyear
df_train['order_month'] = df_train['order_date'].dt.month

df_train['delivered_day'] = df_train['evsd'].dt.day
df_train['delivered_dayofweek'] = df_train['evsd'].dt.dayofweek
df_train['delivered_dayofyear'] = df_train['evsd'].dt.dayofyear
df_train['delivered_month'] = df_train['evsd'].dt.month

df_train['order_month_sin'] = np.sin(2 * np.pi * df_train['order_month'] / 12)
df_train['order_month_cos'] = np.cos(2 * np.pi * df_train['order_month'] / 12)

df_train['order_dayofweek_sin'] = np.sin(2 * np.pi * df_train['order_dayofweek'] / 7)
df_train['order_dayofweek_cos'] = np.cos(2 * np.pi * df_train['order_dayofweek'] / 7)

df_train['delivered_month_sin'] = np.sin(2 * np.pi * df_train['delivered_month'] / 12)
df_train['delivered_month_cos'] = np.cos(2 * np.pi * df_train['delivered_month'] / 12)

df_train['delivered_dayofweek_sin'] = np.sin(2 * np.pi * df_train['delivered_dayofweek'] / 7)
df_train['delivered_dayofweek_cos'] = np.cos(2 * np.pi * df_train['delivered_dayofweek'] / 7)

df_train.drop(['order_month','delivered_month'], axis =1, inplace = True)
display(df_train.head())


df_test['order_day'] = df_test['order_date'].dt.day
df_test['order_dayofweek'] = df_test['order_date'].dt.dayofweek
df_test['order_dayofyear'] = df_test['order_date'].dt.dayofyear
df_test['order_month'] = df_test['order_date'].dt.month

df_test['delivered_day'] = df_test['evsd'].dt.day
df_test['delivered_dayofweek'] = df_test['evsd'].dt.dayofweek
df_test['delivered_dayofyear'] = df_test['evsd'].dt.dayofyear
df_test['delivered_month'] = df_test['evsd'].dt.month

df_test['order_month_sin'] = np.sin(2 * np.pi * df_test['order_month'] / 12)
df_test['order_month_cos'] = np.cos(2 * np.pi * df_test['order_month'] / 12)

df_test['order_dayofweek_sin'] = np.sin(2 * np.pi * df_test['order_dayofweek'] / 7)
df_test['order_dayofweek_cos'] = np.cos(2 * np.pi * df_test['order_dayofweek'] / 7)

df_test['delivered_month_sin'] = np.sin(2 * np.pi * df_test['delivered_month'] / 12)
df_test['delivered_month_cos'] = np.cos(2 * np.pi * df_test['delivered_month'] / 12)

df_test['delivered_dayofweek_sin'] = np.sin(2 * np.pi * df_test['delivered_dayofweek'] / 7)
df_test['delivered_dayofweek_cos'] = np.cos(2 * np.pi * df_test['delivered_dayofweek'] / 7)

df_test.drop(['order_month','delivered_month'], axis =1, inplace = True)
display(df_test.head())

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,po_source_ind_AFT_Lite,row_group_ind_1,row_group_ind_2,row_group_ind_4,row_group_ind_5,row_group_ind_3,row_group_ind_6,row_group_ind_0,row_group_ind_7,d_id_509,d_id_584,d_id_540,d_id_648,d_id_7,d_id_410,d_id_1,d_id_643,d_id_684,d_id_454,d_id_110,d_id_639,d_id_652,d_id_524,d_id_174,d_id_18,d_id_136,d_id_472,d_id_393,d_id_566,d_id_763,d_id_218,d_id_343,d_id_711,d_id_13,d_id_302,d_id_373,d_id_830,d_id_79,d_id_613,d_id_440,d_id_845,d_id_127,d_id_216,d_id_746,d_id_462,d_id_210,d_id_241,order_day,order_dayofweek,order_dayofyear,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train,JFK2_540_30718_67271 ...,12,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,306,14,0,318,-0.500000,8.660254e-01,0.974928,-0.222521,-5.000000e-01,0.866025,0.000000,1.000000
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train,JFK2_540_30718_125389 ...,11,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,6,324,1,3,335,-0.500000,8.660254e-01,-0.781831,0.623490,-2.449294e-16,1.000000,0.433884,-0.900969
2,1,JFK2,648,16750,11165,2022-09-30,2022-10-03,AFT Lite,6,6,6,1,2,train,JFK2_648_16750_11165 ...,3,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,30,4,273,3,0,276,-1.000000,-1.836970e-16,-0.433884,-0.900969,-8.660254e-01,0.500000,0.000000,1.000000
3,1,JFK2,648,16750,27008,2022-10-14,2022-10-17,AFT Lite,6,6,6,2,2,train,JFK2_648_16750_27008 ...,3,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,4,287,17,0,290,-0.866025,5.000000e-01,-0.433884,-0.900969,-8.660254e-01,0.500000,0.000000,1.000000
4,1,JFK2,7,8748,33598,2022-11-15,2022-11-16,AFT Lite,8,8,8,1,1,train,JFK2_7_8748_33598 _2...,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,1,319,16,2,320,-0.500000,8.660254e-01,0.781831,0.623490,-5.000000e-01,0.866025,0.974928,-0.222521

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,po_source_ind_AFT_Lite,row_group_ind_1,row_group_ind_2,row_group_ind_4,row_group_ind_5,row_group_ind_3,row_group_ind_6,row_group_ind_0,row_group_ind_7,d_id_509,d_id_584,d_id_540,d_id_648,d_id_7,d_id_410,d_id_1,d_id_643,d_id_684,d_id_454,d_id_110,d_id_639,d_id_652,d_id_524,d_id_174,d_id_18,d_id_136,d_id_472,d_id_393,d_id_566,d_id_763,d_id_218,d_id_343,d_id_711,d_id_13,d_id_302,d_id_373,d_id_830,d_id_79,d_id_613,d_id_440,d_id_845,d_id_127,d_id_216,d_id_746,d_id_462,d_id_210,d_id_241,order_day,order_dayofweek,order_dayofyear,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos
0,1,JFK2,684,674,45573,2022-12-15,2022-12-19,AFT Lite,42,42,42,3,3,test,JFK2_684_674_45573 _...,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,349,19,0,353,-2.449294e-16,1.0,0.433884,-0.900969,-2.449294e-16,1.000000,0.000000,1.000000
1,1,JFK2,1,19822,110331,2022-12-27,2022-12-30,AFT Lite,6,6,6,0,3,test,JFK2_1_19822_110331 ...,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27,1,361,30,4,364,-2.449294e-16,1.0,0.781831,0.623490,-2.449294e-16,1.000000,-0.433884,-0.900969
2,1,JFK2,509,19749,119943,2022-12-15,2022-12-17,AFT Lite,12,12,12,3,1,test,JFK2_509_19749_119943 ...,2,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,349,17,5,351,-2.449294e-16,1.0,0.433884,-0.900969,-2.449294e-16,1.000000,-0.974928,-0.222521
3,1,JFK2,584,19747,43091,2022-12-20,2022-12-23,AFT Lite,12,12,12,4,3,test,JFK2_584_19747_43091 ...,3,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20,1,354,23,4,357,-2.449294e-16,1.0,0.781831,0.623490,-2.449294e-16,1.000000,-0.433884,-0.900969
4,1,JFK2,540,20260,117854,2022-12-26,2023-01-04,AFT Lite,60,60,60,1,8,test,JFK2_540_20260_117854 ...,9,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,26,0,360,4,2,4,-2.449294e-16,1.0,0.000000,1.000000,5.000000e-01,0.866025,0.974928,-0.222521

In [71]:
req_cols = [col for col in df_train.columns if col not in ['region_id', 'warehouse_id', 'd_id', 'isbn_id', 'order_id', 'order_date', 'evsd', 'po_source_ind', 'tag', 'unique_id', 'row_group_ind','quantity_received', 
                                                           
 'order_month_sin',
 'order_month_cos',
 'order_dayofweek_sin',
 'order_dayofweek_cos',
 'delivered_month_sin',
 'delivered_month_cos',
 'delivered_dayofweek_sin',
 'delivered_dayofweek_cos',
 'order_day',
 'order_dayofweek',
 'order_dayofyear',
 'delivered_day',
 'delivered_dayofweek',
 'delivered_dayofyear','isbn_VC']]

In [ ]:
# ISolation forest : Outliers 
# Neural NEts
#  Blending & Stacking

#  RF , NN and Cat Boost 
# ()

In [72]:
def mae(y_true, predictions):
    y_true, predictions = np.array(y_true), np.array(predictions)
    return np.mean(np.abs(y_true - predictions))

In [73]:
def new_metric(df):
    df['mae'] = df[['quantity_received', 'preds']].apply(lambda row: mae(row['quantity_received'], row['preds']), axis=1)
    final_error = df['mae'].sum()/ df['preds'].sum()
    return final_error

In [74]:
req_cols

['quantity_ordered',
 'quantity_submitted',
 'visibility',
 'order_delivery_days',
 'po_source_ind_AFT_Lite',
 'row_group_ind_1',
 'row_group_ind_2',
 'row_group_ind_4',
 'row_group_ind_5',
 'row_group_ind_3',
 'row_group_ind_6',
 'row_group_ind_0',
 'row_group_ind_7',
 'd_id_509',
 'd_id_584',
 'd_id_540',
 'd_id_648',
 'd_id_7',
 'd_id_410',
 'd_id_1',
 'd_id_643',
 'd_id_684',
 'd_id_454',
 'd_id_110',
 'd_id_639',
 'd_id_652',
 'd_id_524',
 'd_id_174',
 'd_id_18',
 'd_id_136',
 'd_id_472',
 'd_id_393',
 'd_id_566',
 'd_id_763',
 'd_id_218',
 'd_id_343',
 'd_id_711',
 'd_id_13',
 'd_id_302',
 'd_id_373',
 'd_id_830',
 'd_id_79',
 'd_id_613',
 'd_id_440',
 'd_id_845',
 'd_id_127',
 'd_id_216',
 'd_id_746',
 'd_id_462',
 'd_id_210',
 'd_id_241']

In [75]:
df_train[req_cols].head()
# po_source_ind_AFT_Lite

,quantity_ordered,quantity_submitted,visibility,order_delivery_days,po_source_ind_AFT_Lite,row_group_ind_1,row_group_ind_2,row_group_ind_4,row_group_ind_5,row_group_ind_3,row_group_ind_6,row_group_ind_0,row_group_ind_7,d_id_509,d_id_584,d_id_540,d_id_648,d_id_7,d_id_410,d_id_1,d_id_643,d_id_684,d_id_454,d_id_110,d_id_639,d_id_652,d_id_524,d_id_174,d_id_18,d_id_136,d_id_472,d_id_393,d_id_566,d_id_763,d_id_218,d_id_343,d_id_711,d_id_13,d_id_302,d_id_373,d_id_830,d_id_79,d_id_613,d_id_440,d_id_845,d_id_127,d_id_216,d_id_746,d_id_462,d_id_210,d_id_241
0,54,54,9,12,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,60,60,3,11,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,6,6,2,3,1,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,6,6,2,3,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,8,8,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [76]:
from sklearn.preprocessing import QuantileTransformer
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import xgboost as xgb

# Instantiate the transformer
qt = QuantileTransformer()

In [79]:
xtrain =df_train[req_cols].copy()
xvalid = df_test[req_cols].copy()
y_train = df_train['quantity_received']
y_test = df_test['quantity_received']


xtrain[req_cols] = qt.fit_transform(xtrain[req_cols])
xvalid[req_cols] = qt.transform(xvalid[req_cols])

# Create a Random Forest Regressor model with the 

params = {'learning_rate': 0.012474461205653545, 'reg_lambda': 0.0001707023732194043, 
          'reg_alpha': 4.835396220703478e-07, 'subsample': 0.7611297189240918, 
          'colsample_bytree': 0.8042274525172894, 'max_depth': 3, 'n_estimators': 1759}
# rf_model = RandomForestRegressor(n_estimators=30,random_state=42)
# model = xgb.XGBRegressor(
#             # **params,
#             random_state=42,
#             objective='reg:squarederror',
#             n_estimators=150,
#             # learning_rate=learning_rate,
#             # reg_lambda=reg_lambda,
#             # reg_alpha=reg_alpha,
#             # subsample=subsample,
#             # colsample_bytree=colsample_bytree,
#             max_depth=10,
#             eval_metric='mae'
#         )
# model = RandomForestRegressor(
#             # **params,
#             random_state=42,
#             min_samples_leaf=2,
#             n_estimators=10,
#             # max_features='auto',
#             # reg_lambda=reg_lambda,
#             # reg_alpha=reg_alpha,
#             # subsample=subsample,
#             # colsample_bytree=colsample_bytree,
#             max_depth=3,
#             min_samples_split=2
#         )

from catboost import CatBoostRegressor

# Initialize the CatBoost Regressor with the desired parameters
model = CatBoostRegressor(iterations=100,
                          learning_rate=0.1,
                          depth=6,
                          l2_leaf_reg=3,
                          random_seed=42,
                          loss_function='MAE',
                          od_type='Iter',
                          od_wait=20,
                          bagging_temperature=0.8,
                          verbose=100)

# Fit the model on the training data
model.fit(xtrain, y_train,
          eval_set=(xvalid, y_test),
          early_stopping_rounds=20,
          use_best_model=True)



# model.fit(xtrain, y_train)
temp = df_test.copy()
temp['preds'] = model.predict(xvalid)
mae_ = mean_absolute_error(temp['quantity_received'], temp['preds'])
r2_sc = r2_score(temp['quantity_received'], temp['preds'])
print("Mean Absolute Error : ", mae_)
print("R2_score : ", r2_sc)
r2 = r2_sc.copy()
n = len(y_test)
p = xvalid.shape[1]  # number of features in X
adj_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
print("Adjusted R-Square: ", adj_r2)
final_error = new_metric(temp)
print(final_error)

0:	learn: 10.3715827	test: 11.1870358	best: 11.1870358 (0)	total: 254ms	remaining: 25.2s
99:	learn: 3.8204947	test: 4.6804413	best: 4.6804413 (99)	total: 7.46s	remaining: 0us

bestTest = 4.680441267
bestIteration = 99

Mean Absolute Error :  4.680442232801706
R2_score :  0.38226250487839186
Adjusted R-Square:  0.3819418700915451
0.3894713786969811

In [80]:
temp[['preds', 'quantity_received']]

           preds  quantity_received
0      42.275828                 42
1       6.000000                  6
2      11.999840                 12
3      11.999841                 12
4      61.048916                 60
...          ...                ...
98304  11.999841                 12
98305  11.999841                 12
98306   4.000578                  4
98307   0.000160                  0
98308   0.000159                  0

[98309 rows x 2 columns]

In [57]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Define a function to calculate the VIF for each variable
def calc_vif(X):
    # Calculate VIF for each variable in the dataset
    vif = pd.DataFrame()
    vif["Features"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    return vif

# Drop the target variable and any irrelevant features 
X = df_train[req_cols].copy()

# Calculate the initial VIF for each variable
initial_vif = calc_vif(X)

# Remove features with high VIF
while initial_vif['VIF'].max() > 5:
    # Get the name of the variable with the highest VIF
    remove_feature = initial_vif[initial_vif['VIF'] == initial_vif['VIF'].max()]['Features'].values[0]
    print("Removing Feature: ", remove_feature)
    # Drop the variable from the dataset
    X.drop(remove_feature, axis=1, inplace=True)
    # Recalculate the VIF for the remaining variables
    initial_vif = calc_vif(X)

# Print the final set of features after removing multicollinearity
print(X.columns)

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\stats\outliers_influence.py:195: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)
c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1752: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss

Removing Feature:  order_delivery_days

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1752: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss

Removing Feature:  order_dayofyear

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  delivered_dayofyear

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  order_month_sin

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  po_source_ind_AFT_Lite

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  delivered_month_cos

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  delivered_dayofweek

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  quantity_submitted

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  delivered_month_sin

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Removing Feature:  order_dayofweek

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\statsmodels\regression\linear_model.py:1754: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.uncentered_tss

Index(['quantity_ordered', 'visibility', 'd_id_509', 'd_id_584', 'd_id_540',
       'd_id_648', 'd_id_7', 'd_id_410', 'd_id_1', 'd_id_643', 'd_id_684',
       'd_id_454', 'isbn_id_4595', 'isbn_id_14820', 'isbn_id_373',
       'isbn_id_31986', 'isbn_id_27825', 'isbn_id_26550', 'isbn_id_8453',
       'isbn_id_6790', 'isbn_id_19934', 'isbn_id_7865', 'row_group_ind_4',
       'row_group_ind_1', 'row_group_ind_5', 'row_group_ind_3',
       'row_group_ind_2', 'row_group_ind_6', 'row_group_ind_0',
       'row_group_ind_7', 'order_day', 'delivered_day', 'order_month_cos',
       'order_dayofweek_sin', 'order_dayofweek_cos', 'delivered_dayofweek_sin',
       'delivered_dayofweek_cos'],
      dtype='object')

In [25]:
good_cols = ['quantity_ordered', 'visibility', 'd_id_509', 'd_id_584', 'd_id_540',
       'd_id_648', 'd_id_7', 'd_id_410', 'd_id_1', 'd_id_643', 'd_id_684',
       'd_id_454', 'isbn_id_4595', 'isbn_id_14820', 'isbn_id_373',
       'isbn_id_31986', 'isbn_id_27825', 'isbn_id_26550', 'isbn_id_8453',
       'isbn_id_6790', 'isbn_id_19934', 'isbn_id_7865', 'row_group_ind_4',
       'row_group_ind_1', 'row_group_ind_5', 'row_group_ind_3',
       'row_group_ind_2', 'row_group_ind_6', 'row_group_ind_0',
       'row_group_ind_7', 'order_day', 'delivered_day', 'order_month_cos',
       'order_dayofweek_sin', 'order_dayofweek_cos', 'delivered_dayofweek_sin',
       'delivered_dayofweek_cos']

In [59]:
xtrain =df_train[good_cols].copy()
xvalid = df_test[good_cols].copy()
y_train = df_train['quantity_received']
y_test = df_test['quantity_received']


xtrain[good_cols] = qt.fit_transform(xtrain[good_cols])
xvalid[good_cols] = qt.transform(xvalid[good_cols])

# Create a Random Forest Regressor model with the 

params = {'learning_rate': 0.012474461205653545, 'reg_lambda': 0.0001707023732194043, 
          'reg_alpha': 4.835396220703478e-07, 'subsample': 0.7611297189240918, 
          'colsample_bytree': 0.8042274525172894, 'max_depth': 3, 'n_estimators': 1759}
# rf_model = RandomForestRegressor(n_estimators=30,random_state=42)
model = xgb.XGBRegressor(**params,
            random_state=42,
            objective='reg:squarederror',
            # n_estimators=n_estimators,
            # learning_rate=learning_rate,
            # reg_lambda=reg_lambda,
            # reg_alpha=reg_alpha,
            # subsample=subsample,
            # colsample_bytree=colsample_bytree,
            # max_depth=max_depth,
            eval_metric='mae'
        )
model.fit(xtrain, y_train)
temp = df_test.copy()
temp['preds'] = model.predict(xvalid)
mae_ = mean_absolute_error(temp['quantity_received'], temp['preds'])
r2_sc = r2_score(temp['quantity_received'], temp['preds'])
print("Mean Absolute Error : ", mae_)
print("R2_score : ", r2_sc)
r2 = r2_sc.copy()
n = len(y_test)
p = xvalid.shape[1]  # number of features in X
adj_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
print("Adjusted R-Square: ", adj_r2)
final_error = new_metric(temp)
print(final_error)

Mean Absolute Error :  4.482211872993045
R2_score :  0.6456970187497457
Adjusted R-Square:  0.6455636201855075
0.35977250752473444

In [84]:
"""Uncomment for tuning the model"""
import optuna
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.svm import SVR

imp_features = ['quantity_ordered', 'quantity_submitted', 'order_delivery_days', 'd_id_509', 'd_id_584', 'd_id_540', 'd_id_648', 'd_id_410', 'row_group_ind_6']


def run(trial):

    xtrain =df_train[req_cols].copy()
    xvalid = df_test[req_cols].copy()
    y_train = df_train['quantity_received']
    y_test = df_test['quantity_received']


    xtrain[req_cols] = qt.fit_transform(xtrain[req_cols])
    xvalid[req_cols] = qt.transform(xvalid[req_cols])

    # Define the hyperparameters to be tuned
    params = {
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 0.1),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, 100),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 0.1, 10.0),
        'random_strength': trial.suggest_float('random_strength', 1e-9, 10.0),
        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.01, 100.0),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 100),

        # 'learning_rate': trial.suggest_loguniform('learning_rate', low=0.01, high=0.5),
        # 'depth': trial.suggest_int('depth', 3, 10),
        # 'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', low=1e-5, high=1e-1),
        # 'bagging_temperature': trial.suggest_loguniform('bagging_temperature', low=0.01, high=100.0),
        # 'random_strength': trial.suggest_loguniform('random_strength', low=1e-5, high=1e-1),
        # 'od_type': 'Iter',
        # 'od_wait': 50,
        # 'loss_function': 'MAE'
    }

    # Create the SVR model with the given hyperparameters
    # Train model with current hyperparameters
    model = CatBoostRegressor(**params, loss_function='MAE')
    # model.fit(X_train, y_train)
    model.fit(xtrain, y_train, verbose=False)
    preds_valid = model.predict(xvalid)
    mae_ = mean_absolute_error(y_test, preds_valid)
    r2_sc = r2_score(y_test, preds_valid)

    temp = df_test.copy()
    temp['preds'] = model.predict(xvalid)

    print("Mean Absolute Error : ", mae_)
    print("R2_score : ", r2_sc)
    r2 = r2_sc.copy()
    n = len(y_test)
    p = xvalid.shape[1]  # number of features in X
    adj_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
    print("Adjusted R-Square: ", adj_r2)

    
    final_error = new_metric(temp)
    print("Custom Error: ",final_error)
    del temp
    return final_error

study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=100)

# study.best_params

[I 2023-05-01 18:59:51,079] A new study created in memory with name: no-name-fbcb85c4-93a8-4c52-b7c6-cd2705432b6e

Mean Absolute Error :  3.556678414970011
R2_score :  0.5485884714795741
Adjusted R-Square:  0.5483541676848873

[I 2023-05-01 19:00:34,250] Trial 0 finished with value: 0.26762005700635555 and parameters: {'learning_rate': 0.08518047735630305, 'max_depth': 3, 'n_estimators': 1000, 'l2_leaf_reg': 3.5663433420772583, 'random_strength': 5.737270454572877, 'bagging_temperature': 81.27911120782699, 'min_data_in_leaf': 62}. Best is trial 0 with value: 0.26762005700635555.

Custom Error:  0.26762005700635555
Mean Absolute Error :  4.739598236074501
R2_score :  0.5974220004175116
Adjusted R-Square:  0.5972130435189832

[I 2023-05-01 19:01:16,277] Trial 1 finished with value: 0.3971514257221703 and parameters: {'learning_rate': 0.004269681245266157, 'max_depth': 7, 'n_estimators': 800, 'l2_leaf_reg': 6.844319570220772, 'random_strength': 7.39915431581843, 'bagging_temperature': 42.672956053414055, 'min_data_in_leaf': 49}. Best is trial 0 with value: 0.26762005700635555.

Custom Error:  0.3971514257221703
Mean Absolute Error :  3.882153834419485
R2_score :  0.5276196816899507
Adjusted R-Square:  0.5273744941080601

[I 2023-05-01 19:01:48,901] Trial 2 finished with value: 0.2990917053868111 and parameters: {'learning_rate': 0.03583166929370311, 'max_depth': 3, 'n_estimators': 900, 'l2_leaf_reg': 7.241338908061152, 'random_strength': 5.6093853173110455, 'bagging_temperature': 16.054600137363316, 'min_data_in_leaf': 62}. Best is trial 0 with value: 0.26762005700635555.

Custom Error:  0.2990917053868111
Mean Absolute Error :  4.16149476585333
R2_score :  0.5303971203642488
Adjusted R-Square:  0.5301533744035394

[I 2023-05-01 19:02:21,617] Trial 3 finished with value: 0.3306183157189736 and parameters: {'learning_rate': 0.0073298000601081685, 'max_depth': 8, 'n_estimators': 700, 'l2_leaf_reg': 8.056342092514635, 'random_strength': 2.0779726493552984, 'bagging_temperature': 27.423060117172202, 'min_data_in_leaf': 56}. Best is trial 0 with value: 0.26762005700635555.

Custom Error:  0.3306183157189736
Mean Absolute Error :  3.2092998922786364
R2_score :  0.7619807961298475
Adjusted R-Square:  0.7618572529787501

[I 2023-05-01 19:02:32,290] Trial 4 finished with value: 0.23325460609891674 and parameters: {'learning_rate': 0.08966357692697273, 'max_depth': 9, 'n_estimators': 100, 'l2_leaf_reg': 9.207428502499337, 'random_strength': 8.36531302779265, 'bagging_temperature': 83.07371514483351, 'min_data_in_leaf': 11}. Best is trial 4 with value: 0.23325460609891674.

Custom Error:  0.23325460609891674
Mean Absolute Error :  3.1314116629097875
R2_score :  0.6642401296484346
Adjusted R-Square:  0.6640658544986954

[I 2023-05-01 19:03:06,703] Trial 5 finished with value: 0.22748472681040785 and parameters: {'learning_rate': 0.08864929186436224, 'max_depth': 4, 'n_estimators': 800, 'l2_leaf_reg': 5.291651006860536, 'random_strength': 9.858363182597435, 'bagging_temperature': 91.43362822721902, 'min_data_in_leaf': 41}. Best is trial 5 with value: 0.22748472681040785.

Custom Error:  0.22748472681040785
Mean Absolute Error :  3.205936222556118
R2_score :  0.6730815555642847
Adjusted R-Square:  0.6729118695300458

[I 2023-05-01 19:03:40,808] Trial 6 finished with value: 0.23385910788229541 and parameters: {'learning_rate': 0.06155369467379925, 'max_depth': 5, 'n_estimators': 600, 'l2_leaf_reg': 7.735737171417175, 'random_strength': 8.15640079003918, 'bagging_temperature': 90.77739395050943, 'min_data_in_leaf': 95}. Best is trial 5 with value: 0.22748472681040785.

Custom Error:  0.23385910788229541
Mean Absolute Error :  3.380694423856899
R2_score :  0.6222338660484262
Adjusted R-Square:  0.6220377876740455

[I 2023-05-01 19:04:00,994] Trial 7 finished with value: 0.2507930238096674 and parameters: {'learning_rate': 0.0675820109553051, 'max_depth': 4, 'n_estimators': 400, 'l2_leaf_reg': 6.6645955833038535, 'random_strength': 4.887219769977652, 'bagging_temperature': 64.6639705869479, 'min_data_in_leaf': 87}. Best is trial 5 with value: 0.22748472681040785.

Custom Error:  0.2507930238096674
Mean Absolute Error :  3.7518487854285696
R2_score :  0.5963810705216921
Adjusted R-Square:  0.5961715733316355

[I 2023-05-01 19:04:13,498] Trial 8 finished with value: 0.2847341701424763 and parameters: {'learning_rate': 0.09867842412983621, 'max_depth': 7, 'n_estimators': 100, 'l2_leaf_reg': 6.23254783644391, 'random_strength': 1.7868310914761827, 'bagging_temperature': 3.8331880432027794, 'min_data_in_leaf': 45}. Best is trial 5 with value: 0.22748472681040785.

Custom Error:  0.2847341701424763
Mean Absolute Error :  7.879290803181221
R2_score :  0.2148115290283067
Adjusted R-Square:  0.21440397931663668

[I 2023-05-01 19:04:25,639] Trial 9 finished with value: 0.9086572982328605 and parameters: {'learning_rate': 0.012989300957748574, 'max_depth': 6, 'n_estimators': 100, 'l2_leaf_reg': 4.520278154348266, 'random_strength': 2.2836294501291787, 'bagging_temperature': 83.80056512858519, 'min_data_in_leaf': 65}. Best is trial 5 with value: 0.22748472681040785.

Custom Error:  0.9086572982328605
Mean Absolute Error :  2.8844417363104244
R2_score :  0.7686088587388975
Adjusted R-Square:  0.7684887558637403

[I 2023-05-01 19:04:59,235] Trial 10 finished with value: 0.20503715176429113 and parameters: {'learning_rate': 0.07788360666568024, 'max_depth': 10, 'n_estimators': 400, 'l2_leaf_reg': 1.2227249315021909, 'random_strength': 9.9462125494656, 'bagging_temperature': 99.31588963282522, 'min_data_in_leaf': 18}. Best is trial 10 with value: 0.20503715176429113.

Custom Error:  0.20503715176429113
Mean Absolute Error :  2.8274384583557977
R2_score :  0.7830718258425117
Adjusted R-Square:  0.7829592299268819

[I 2023-05-01 19:05:32,048] Trial 11 finished with value: 0.20006977908437648 and parameters: {'learning_rate': 0.08144301139047999, 'max_depth': 10, 'n_estimators': 400, 'l2_leaf_reg': 0.5733778942572089, 'random_strength': 9.88584994832346, 'bagging_temperature': 98.27351739254749, 'min_data_in_leaf': 19}. Best is trial 11 with value: 0.20006977908437648.

Custom Error:  0.20006977908437648
Mean Absolute Error :  2.89855955902615
R2_score :  0.7470329724079054
Adjusted R-Square:  0.7469016706339129

[I 2023-05-01 19:06:01,398] Trial 12 finished with value: 0.20647654812224156 and parameters: {'learning_rate': 0.0721633712791267, 'max_depth': 10, 'n_estimators': 400, 'l2_leaf_reg': 0.3912705018117918, 'random_strength': 9.91225213663835, 'bagging_temperature': 65.16563110518705, 'min_data_in_leaf': 6}. Best is trial 11 with value: 0.20006977908437648.

Custom Error:  0.20647654812224156
Mean Absolute Error :  2.9173906662150006
R2_score :  0.7578735345293106
Adjusted R-Square:  0.7577478595164464

[I 2023-05-01 19:06:35,825] Trial 13 finished with value: 0.20764672174700127 and parameters: {'learning_rate': 0.05286712846449799, 'max_depth': 10, 'n_estimators': 400, 'l2_leaf_reg': 0.7766740190970487, 'random_strength': 9.401725154566009, 'bagging_temperature': 96.93051819747707, 'min_data_in_leaf': 23}. Best is trial 11 with value: 0.20006977908437648.

Custom Error:  0.20764672174700127
Mean Absolute Error :  3.0128896464371766
R2_score :  0.7621038603238955
Adjusted R-Square:  0.7619803810488975

[I 2023-05-01 19:06:56,726] Trial 14 finished with value: 0.2155243637762789 and parameters: {'learning_rate': 0.07659615384165867, 'max_depth': 9, 'n_estimators': 300, 'l2_leaf_reg': 1.9333254109629419, 'random_strength': 7.175395992758569, 'bagging_temperature': 99.00543137924922, 'min_data_in_leaf': 25}. Best is trial 11 with value: 0.20006977908437648.

Custom Error:  0.2155243637762789
Mean Absolute Error :  2.9285689085901465
R2_score :  0.7649850971928167
Adjusted R-Square:  0.7648631134151401

[I 2023-05-01 19:07:20,750] Trial 15 finished with value: 0.20794208142432824 and parameters: {'learning_rate': 0.07776209511068398, 'max_depth': 9, 'n_estimators': 300, 'l2_leaf_reg': 1.8487671189343513, 'random_strength': 8.75723560484249, 'bagging_temperature': 70.66730007776263, 'min_data_in_leaf': 27}. Best is trial 11 with value: 0.20006977908437648.

Custom Error:  0.20794208142432824
Mean Absolute Error :  2.8209147919179234
R2_score :  0.7816388281055682
Adjusted R-Square:  0.7815254883967778

[I 2023-05-01 19:08:03,638] Trial 16 finished with value: 0.19991265419659066 and parameters: {'learning_rate': 0.059090672579803195, 'max_depth': 10, 'n_estimators': 500, 'l2_leaf_reg': 2.857817737228464, 'random_strength': 9.787924464448945, 'bagging_temperature': 99.47845089730905, 'min_data_in_leaf': 15}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.19991265419659066
Mean Absolute Error :  2.9156379869844224
R2_score :  0.7367526250135124
Adjusted R-Square:  0.7366159872561586

[I 2023-05-01 19:08:42,827] Trial 17 finished with value: 0.20770036931925906 and parameters: {'learning_rate': 0.055419107987996076, 'max_depth': 8, 'n_estimators': 600, 'l2_leaf_reg': 2.9189913425388703, 'random_strength': 6.9046152923233315, 'bagging_temperature': 56.620271626051355, 'min_data_in_leaf': 3}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20770036931925906
Mean Absolute Error :  2.935201663317287
R2_score :  0.7550608085247215
Adjusted R-Square:  0.7549336735748936

[I 2023-05-01 19:09:17,832] Trial 18 finished with value: 0.20902379425028522 and parameters: {'learning_rate': 0.04194879241377027, 'max_depth': 8, 'n_estimators': 500, 'l2_leaf_reg': 0.22163386659875428, 'random_strength': 8.783081921436127, 'bagging_temperature': 76.05718724091649, 'min_data_in_leaf': 32}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20902379425028522
Mean Absolute Error :  2.9546019602536164
R2_score :  0.7668869776518541
Adjusted R-Square:  0.7667659810395032

[I 2023-05-01 19:09:35,382] Trial 19 finished with value: 0.2097163473784244 and parameters: {'learning_rate': 0.06260324938236937, 'max_depth': 10, 'n_estimators': 200, 'l2_leaf_reg': 2.6949800631411254, 'random_strength': 8.9648363082005, 'bagging_temperature': 87.97555227265713, 'min_data_in_leaf': 14}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.2097163473784244
Mean Absolute Error :  2.8438151380994254
R2_score :  0.7757969915265859
Adjusted R-Square:  0.7756806196301088

[I 2023-05-01 19:10:09,140] Trial 20 finished with value: 0.20135059473726516 and parameters: {'learning_rate': 0.0996657522260392, 'max_depth': 9, 'n_estimators': 500, 'l2_leaf_reg': 1.536432024141154, 'random_strength': 7.8758372634130005, 'bagging_temperature': 74.93384543831564, 'min_data_in_leaf': 2}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20135059473726516
Mean Absolute Error :  2.8848479996908427
R2_score :  0.7527025711042259
Adjusted R-Square:  0.7525742121183655

[I 2023-05-01 19:10:44,587] Trial 21 finished with value: 0.20551909203755364 and parameters: {'learning_rate': 0.0986175134829726, 'max_depth': 9, 'n_estimators': 500, 'l2_leaf_reg': 1.7035615028446545, 'random_strength': 8.076799815036003, 'bagging_temperature': 75.93743311415263, 'min_data_in_leaf': 1}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20551909203755364
Mean Absolute Error :  2.828234319097397
R2_score :  0.775884930424664
Adjusted R-Square:  0.7757686041726073

[I 2023-05-01 19:11:38,236] Trial 22 finished with value: 0.201015737491229 and parameters: {'learning_rate': 0.08527617152610094, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 1.1488764566046652, 'random_strength': 9.235412166644478, 'bagging_temperature': 90.296517410008, 'min_data_in_leaf': 33}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.201015737491229
Mean Absolute Error :  2.8381847569565073
R2_score :  0.7528284487161111
Adjusted R-Square:  0.7527001550666461

[I 2023-05-01 19:12:31,767] Trial 23 finished with value: 0.20155295886737518 and parameters: {'learning_rate': 0.06883925617538661, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 0.32007607007530525, 'random_strength': 9.340360970798042, 'bagging_temperature': 89.42535349831422, 'min_data_in_leaf': 35}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20155295886737518
Mean Absolute Error :  2.918225641656025
R2_score :  0.7438432780154449
Adjusted R-Square:  0.7437103206401819

[I 2023-05-01 19:13:07,243] Trial 24 finished with value: 0.20770959129010813 and parameters: {'learning_rate': 0.08392633771636684, 'max_depth': 8, 'n_estimators': 600, 'l2_leaf_reg': 2.7520775414379255, 'random_strength': 8.907355547488185, 'bagging_temperature': 97.73277560573824, 'min_data_in_leaf': 36}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20770959129010813
Mean Absolute Error :  2.9661254190349395
R2_score :  0.7452312442211335
Adjusted R-Square:  0.7450990072655505

[I 2023-05-01 19:13:35,727] Trial 25 finished with value: 0.2113976271721101 and parameters: {'learning_rate': 0.06447079990620477, 'max_depth': 10, 'n_estimators': 300, 'l2_leaf_reg': 1.094233388010504, 'random_strength': 9.961796300423659, 'bagging_temperature': 91.40870587567831, 'min_data_in_leaf': 17}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.2113976271721101
Mean Absolute Error :  2.891716108683179
R2_score :  0.752240588007088
Adjusted R-Square:  0.7521119892302921

[I 2023-05-01 19:14:22,250] Trial 26 finished with value: 0.20627444738477244 and parameters: {'learning_rate': 0.07220317079129733, 'max_depth': 9, 'n_estimators': 700, 'l2_leaf_reg': 2.315618234397018, 'random_strength': 9.079159409350408, 'bagging_temperature': 83.0266389633727, 'min_data_in_leaf': 29}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.20627444738477244
Mean Absolute Error :  3.03602916756171
R2_score :  0.7116781598751362
Adjusted R-Square:  0.7115285072921511

[I 2023-05-01 19:14:51,972] Trial 27 finished with value: 0.21804422034529924 and parameters: {'learning_rate': 0.09122276240507914, 'max_depth': 6, 'n_estimators': 500, 'l2_leaf_reg': 1.105458463161835, 'random_strength': 7.846953499597106, 'bagging_temperature': 94.53812368549939, 'min_data_in_leaf': 17}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.21804422034529924
Mean Absolute Error :  2.9750704215107624
R2_score :  0.7720066151599342
Adjusted R-Square:  0.7718882758800167

[I 2023-05-01 19:15:13,587] Trial 28 finished with value: 0.21248386887994747 and parameters: {'learning_rate': 0.07958366028425617, 'max_depth': 10, 'n_estimators': 200, 'l2_leaf_reg': 3.7339425130057924, 'random_strength': 6.5366492334907695, 'bagging_temperature': 98.98469228097804, 'min_data_in_leaf': 11}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.21248386887994747
Mean Absolute Error :  2.946499245248586
R2_score :  0.7114707921108939
Adjusted R-Square:  0.7113210318942952

[I 2023-05-01 19:16:09,328] Trial 29 finished with value: 0.2107098917154579 and parameters: {'learning_rate': 0.08349210210358306, 'max_depth': 7, 'n_estimators': 1000, 'l2_leaf_reg': 3.5501171451505025, 'random_strength': 8.455308061005448, 'bagging_temperature': 82.99733238057233, 'min_data_in_leaf': 75}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.2107098917154579
Mean Absolute Error :  2.8407075957474617
R2_score :  0.7596054719730894
Adjusted R-Square:  0.7594806959171405
Custom Error:  0.20129224153026384

[I 2023-05-01 19:17:18,980] Trial 30 finished with value: 0.20129224153026384 and parameters: {'learning_rate': 0.09198907897829384, 'max_depth': 8, 'n_estimators': 600, 'l2_leaf_reg': 0.8733804867245103, 'random_strength': 9.26793659674138, 'bagging_temperature': 88.84937296394715, 'min_data_in_leaf': 22}. Best is trial 16 with value: 0.19991265419659066.

Mean Absolute Error :  2.862805567852472
R2_score :  0.7545243339366617
Adjusted R-Square:  0.7543969205313142

[I 2023-05-01 19:18:08,531] Trial 31 finished with value: 0.2033856764673592 and parameters: {'learning_rate': 0.09199347813726995, 'max_depth': 9, 'n_estimators': 600, 'l2_leaf_reg': 0.7846758574440638, 'random_strength': 9.376385448340782, 'bagging_temperature': 86.97532253290694, 'min_data_in_leaf': 23}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.2033856764673592
Mean Absolute Error :  2.8474170360615503
R2_score :  0.7461566008024972
Adjusted R-Square:  0.7460248441504616
Custom Error:  0.2023287867190596

[I 2023-05-01 19:19:00,261] Trial 32 finished with value: 0.2023287867190596 and parameters: {'learning_rate': 0.08448489923785918, 'max_depth': 8, 'n_estimators': 800, 'l2_leaf_reg': 0.14956681479000605, 'random_strength': 9.384105421970101, 'bagging_temperature': 92.1661463584268, 'min_data_in_leaf': 40}. Best is trial 16 with value: 0.19991265419659066.

Mean Absolute Error :  2.8150951610689954
R2_score :  0.7829965581701167
Adjusted R-Square:  0.7828839231870283

[I 2023-05-01 19:19:51,187] Trial 33 finished with value: 0.19999576082181597 and parameters: {'learning_rate': 0.0927241872284966, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.177896653556913, 'random_strength': 7.72848300270294, 'bagging_temperature': 80.5067017422589, 'min_data_in_leaf': 51}. Best is trial 16 with value: 0.19991265419659066.

Custom Error:  0.19999576082181597
Mean Absolute Error :  2.7953146085835185
R2_score :  0.7727558734525516
Adjusted R-Square:  0.772637923072895

[I 2023-05-01 19:20:45,239] Trial 34 finished with value: 0.19798582828232061 and parameters: {'learning_rate': 0.07315042988441062, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.1685080640446888, 'random_strength': 7.6592881172895435, 'bagging_temperature': 79.78687038735092, 'min_data_in_leaf': 57}. Best is trial 34 with value: 0.19798582828232061.

Custom Error:  0.19798582828232061
Mean Absolute Error :  2.8650613320082976
R2_score :  0.7406424249416942
Adjusted R-Square:  0.740507806173281
Custom Error:  0.2039487660571607

[I 2023-05-01 19:21:51,672] Trial 35 finished with value: 0.2039487660571607 and parameters: {'learning_rate': 0.07024102325052518, 'max_depth': 9, 'n_estimators': 900, 'l2_leaf_reg': 2.2528710897608915, 'random_strength': 7.413803514412333, 'bagging_temperature': 79.62749324523648, 'min_data_in_leaf': 51}. Best is trial 34 with value: 0.19798582828232061.

Mean Absolute Error :  2.7887609508739595
R2_score :  0.7796029354039704
Adjusted R-Square:  0.7794885389712033

[I 2023-05-01 19:23:00,667] Trial 36 finished with value: 0.19790418777738894 and parameters: {'learning_rate': 0.07561116538371458, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.516157169068707, 'random_strength': 6.298515779429497, 'bagging_temperature': 42.51920460946885, 'min_data_in_leaf': 63}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.19790418777738894
Mean Absolute Error :  2.8929019009973334
R2_score :  0.7489104450661292
Adjusted R-Square:  0.7487801177886668

[I 2023-05-01 19:23:47,683] Trial 37 finished with value: 0.20604261026377105 and parameters: {'learning_rate': 0.057544245008492145, 'max_depth': 9, 'n_estimators': 800, 'l2_leaf_reg': 3.3664745949429102, 'random_strength': 5.734144223524314, 'bagging_temperature': 38.98835317090271, 'min_data_in_leaf': 65}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.20604261026377105
Mean Absolute Error :  3.7395749085803307
R2_score :  0.5271616925081821
Adjusted R-Square:  0.5269162672083858

[I 2023-05-01 19:24:24,442] Trial 38 finished with value: 0.28528642906211626 and parameters: {'learning_rate': 0.05900632352104417, 'max_depth': 3, 'n_estimators': 700, 'l2_leaf_reg': 4.185764247248523, 'random_strength': 6.373014591894637, 'bagging_temperature': 50.04995167923403, 'min_data_in_leaf': 58}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.28528642906211626
Mean Absolute Error :  2.854165133272566
R2_score :  0.7457793228782873
Adjusted R-Square:  0.745647370401281

[I 2023-05-01 19:25:47,823] Trial 39 finished with value: 0.20294963752935555 and parameters: {'learning_rate': 0.07474222519934445, 'max_depth': 10, 'n_estimators': 900, 'l2_leaf_reg': 3.092013061691862, 'random_strength': 7.6952516719790784, 'bagging_temperature': 38.71896104320174, 'min_data_in_leaf': 73}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.20294963752935555
Mean Absolute Error :  2.9379572827469818
R2_score :  0.7400704456223051
Adjusted R-Square:  0.7399355299697483

[I 2023-05-01 19:26:59,361] Trial 40 finished with value: 0.2101791163847379 and parameters: {'learning_rate': 0.04492595432545125, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.3055420538796993, 'random_strength': 5.0243917892921806, 'bagging_temperature': 68.85270453443424, 'min_data_in_leaf': 54}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.2101791163847379
Mean Absolute Error :  2.823883365324698
R2_score :  0.7622556534992908
Adjusted R-Square:  0.7621322530120834
Custom Error:  0.20046705281941243

[I 2023-05-01 19:27:58,490] Trial 41 finished with value: 0.20046705281941243 and parameters: {'learning_rate': 0.06705120875527111, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.564361421023018, 'random_strength': 8.310590532795507, 'bagging_temperature': 94.78108718444575, 'min_data_in_leaf': 47}. Best is trial 36 with value: 0.19790418777738894.

Mean Absolute Error :  2.8212679290147773
R2_score :  0.7747695544536846
Adjusted R-Square:  0.7746526492690884

[I 2023-05-01 19:28:55,672] Trial 42 finished with value: 0.20019474319492228 and parameters: {'learning_rate': 0.0799838359931511, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.0442520293175317, 'random_strength': 7.481124160047803, 'bagging_temperature': 79.74409328930732, 'min_data_in_leaf': 75}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.20019474319492228
Mean Absolute Error :  3.42069665313118
R2_score :  0.6168941919537807
Adjusted R-Square:  0.6166953420376388

[I 2023-05-01 19:29:30,243] Trial 43 finished with value: 0.25471903158909054 and parameters: {'learning_rate': 0.07423096419884377, 'max_depth': 4, 'n_estimators': 800, 'l2_leaf_reg': 1.9547314869585557, 'random_strength': 8.299014428832132, 'bagging_temperature': 56.78884034111135, 'min_data_in_leaf': 69}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.25471903158909054
Mean Absolute Error :  2.856459221417498
R2_score :  0.7512532953863023
Adjusted R-Square:  0.7511241841582442

[I 2023-05-01 19:30:27,852] Trial 44 finished with value: 0.2032375044260324 and parameters: {'learning_rate': 0.061814989053712854, 'max_depth': 9, 'n_estimators': 900, 'l2_leaf_reg': 3.8243408768558877, 'random_strength': 6.8883025757730065, 'bagging_temperature': 86.35381991873655, 'min_data_in_leaf': 82}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.2032375044260324
Mean Absolute Error :  2.861172831610872
R2_score :  0.7632001331101692
Adjusted R-Square:  0.76307722285226

[I 2023-05-01 19:31:09,038] Trial 45 finished with value: 0.2034023300920912 and parameters: {'learning_rate': 0.0660853138592325, 'max_depth': 10, 'n_estimators': 500, 'l2_leaf_reg': 4.531347606889023, 'random_strength': 6.034083385609077, 'bagging_temperature': 99.77304424895404, 'min_data_in_leaf': 59}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.2034023300920912
Mean Absolute Error :  2.876626077085731
R2_score :  0.7590370734548006
Adjusted R-Square:  0.7589120023733122
Custom Error:  0.20439513931534267

[I 2023-05-01 19:31:57,911] Trial 46 finished with value: 0.20439513931534267 and parameters: {'learning_rate': 0.07171088672855871, 'max_depth': 10, 'n_estimators': 400, 'l2_leaf_reg': 1.452942788188238, 'random_strength': 8.502945271571082, 'bagging_temperature': 81.04767979201452, 'min_data_in_leaf': 42}. Best is trial 36 with value: 0.19790418777738894.

Mean Absolute Error :  2.875712075633582
R2_score :  0.7519252883538607
Adjusted R-Square:  0.7517965259217292
Custom Error:  0.20432615550986127

[I 2023-05-01 19:32:54,258] Trial 47 finished with value: 0.20432615550986127 and parameters: {'learning_rate': 0.0805413267395127, 'max_depth': 9, 'n_estimators': 700, 'l2_leaf_reg': 3.3291944643244493, 'random_strength': 9.708608221783349, 'bagging_temperature': 92.72684909123686, 'min_data_in_leaf': 52}. Best is trial 36 with value: 0.19790418777738894.

Mean Absolute Error :  2.894911371866927
R2_score :  0.7355283010464502
Adjusted R-Square:  0.7353910278074277
Custom Error:  0.20643696924074673

[I 2023-05-01 19:33:42,722] Trial 48 finished with value: 0.20643696924074673 and parameters: {'learning_rate': 0.07515498665656363, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 2.055701459258921, 'random_strength': 7.168804645563515, 'bagging_temperature': 28.92169808908242, 'min_data_in_leaf': 62}. Best is trial 36 with value: 0.19790418777738894.

Mean Absolute Error :  2.966748948372904
R2_score :  0.7216801075911274
Adjusted R-Square:  0.7215356464889886

[I 2023-05-01 19:34:13,994] Trial 49 finished with value: 0.21203598528239906 and parameters: {'learning_rate': 0.08792332737352074, 'max_depth': 7, 'n_estimators': 500, 'l2_leaf_reg': 1.6365289768281444, 'random_strength': 8.009975464898474, 'bagging_temperature': 95.22118034444, 'min_data_in_leaf': 9}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.21203598528239906
Mean Absolute Error :  2.9338616791454974
R2_score :  0.7599870758396837
Adjusted R-Square:  0.7598624978540728

[I 2023-05-01 19:34:41,831] Trial 50 finished with value: 0.20926061337378266 and parameters: {'learning_rate': 0.050766476232033515, 'max_depth': 9, 'n_estimators': 400, 'l2_leaf_reg': 2.50196994832189, 'random_strength': 8.771070720737802, 'bagging_temperature': 83.93914704358997, 'min_data_in_leaf': 45}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.20926061337378266
Mean Absolute Error :  2.8046362999594976
R2_score :  0.7690024807536475
Adjusted R-Square:  0.7688825821868119

[I 2023-05-01 19:35:36,064] Trial 51 finished with value: 0.19900210158510773 and parameters: {'learning_rate': 0.08034806806861265, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.8563775669975024, 'random_strength': 7.485527743919251, 'bagging_temperature': 79.40418312617498, 'min_data_in_leaf': 81}. Best is trial 36 with value: 0.19790418777738894.

Custom Error:  0.19900210158510773
Mean Absolute Error :  2.7839078973353124
R2_score :  0.7836247625241849
Adjusted R-Square:  0.7835124536086749

[I 2023-05-01 19:36:35,108] Trial 52 finished with value: 0.1971839088035899 and parameters: {'learning_rate': 0.07732391967235773, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.9088803704508064, 'random_strength': 7.602760335751489, 'bagging_temperature': 72.80335644209443, 'min_data_in_leaf': 100}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.1971839088035899
Mean Absolute Error :  2.8308450516788546
R2_score :  0.7642239528607053
Adjusted R-Square:  0.764101574013355

[I 2023-05-01 19:37:33,948] Trial 53 finished with value: 0.2006642070998985 and parameters: {'learning_rate': 0.07875550240355464, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.955746532041026, 'random_strength': 7.61738201392611, 'bagging_temperature': 69.92373342376985, 'min_data_in_leaf': 100}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.2006642070998985
Mean Absolute Error :  2.798169778354546
R2_score :  0.7992654824388061
Adjusted R-Square:  0.7991612917918739

[I 2023-05-01 19:38:23,174] Trial 54 finished with value: 0.19819267511974606 and parameters: {'learning_rate': 0.08667848633498791, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.1496969209589407, 'random_strength': 7.001119496843499, 'bagging_temperature': 73.39414765689851, 'min_data_in_leaf': 81}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.19819267511974606
Mean Absolute Error :  2.9084984591897136
R2_score :  0.7475649213228235
Adjusted R-Square:  0.7474338956553135

[I 2023-05-01 19:39:21,798] Trial 55 finished with value: 0.2073021017694513 and parameters: {'learning_rate': 0.07606655707794904, 'max_depth': 9, 'n_estimators': 800, 'l2_leaf_reg': 4.008738915834138, 'random_strength': 6.902909233079374, 'bagging_temperature': 74.07165149144689, 'min_data_in_leaf': 90}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.2073021017694513
Mean Absolute Error :  3.10082632118197
R2_score :  0.6855358658984099
Adjusted R-Square:  0.6853726442364501

[I 2023-05-01 19:40:05,646] Trial 56 finished with value: 0.22392042217403005 and parameters: {'learning_rate': 0.06991749960721831, 'max_depth': 5, 'n_estimators': 900, 'l2_leaf_reg': 3.2125940376397306, 'random_strength': 7.178762810129748, 'bagging_temperature': 64.39447619366274, 'min_data_in_leaf': 83}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.22392042217403005
Mean Absolute Error :  2.83132208381111
R2_score :  0.7675698408189252
Adjusted R-Square:  0.7674491986446452

[I 2023-05-01 19:41:22,876] Trial 57 finished with value: 0.20103524114979354 and parameters: {'learning_rate': 0.08679080023035177, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 3.5627953244054105, 'random_strength': 6.392641109732323, 'bagging_temperature': 76.57916930506285, 'min_data_in_leaf': 92}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.20103524114979354
Mean Absolute Error :  2.940171286813887
R2_score :  0.7335162590240656
Adjusted R-Square:  0.7333779414406896

[I 2023-05-01 19:42:12,165] Trial 58 finished with value: 0.2103616117286879 and parameters: {'learning_rate': 0.06479717661826175, 'max_depth': 9, 'n_estimators': 700, 'l2_leaf_reg': 2.8428981409156115, 'random_strength': 5.1568562932579525, 'bagging_temperature': 65.08803789606507, 'min_data_in_leaf': 81}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.2103616117286879
Mean Absolute Error :  2.8511653730976163
R2_score :  0.7589109596201793
Adjusted R-Square:  0.7587858230796848
Custom Error:  0.20270563496704183

[I 2023-05-01 19:44:05,709] Trial 59 finished with value: 0.20270563496704183 and parameters: {'learning_rate': 0.08269793333167802, 'max_depth': 10, 'n_estimators': 1000, 'l2_leaf_reg': 2.6734523422139898, 'random_strength': 6.068931474872838, 'bagging_temperature': 72.86659271422847, 'min_data_in_leaf': 96}. Best is trial 52 with value: 0.1971839088035899.

Mean Absolute Error :  2.924449754750967
R2_score :  0.7492511283212031
Adjusted R-Square:  0.7491209778743584

[I 2023-05-01 19:45:02,539] Trial 60 finished with value: 0.20932056540763383 and parameters: {'learning_rate': 0.06785086131470604, 'max_depth': 9, 'n_estimators': 700, 'l2_leaf_reg': 4.958962886104052, 'random_strength': 5.4191208941704625, 'bagging_temperature': 85.6005287663709, 'min_data_in_leaf': 69}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.20932056540763383
Mean Absolute Error :  2.832628345981245
R2_score :  0.7531495111148796
Adjusted R-Square:  0.753021384111886

[I 2023-05-01 19:46:02,200] Trial 61 finished with value: 0.20144872023395038 and parameters: {'learning_rate': 0.08905795032612698, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.4602279821732633, 'random_strength': 7.997806901903672, 'bagging_temperature': 79.38705846328607, 'min_data_in_leaf': 79}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.20144872023395038
Mean Absolute Error :  2.837657625810641
R2_score :  0.7506321486401882
Adjusted R-Square:  0.7505027150077819

[I 2023-05-01 19:46:59,370] Trial 62 finished with value: 0.20170162310969839 and parameters: {'learning_rate': 0.09560929500243008, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 3.3055586275184297, 'random_strength': 7.486339646632821, 'bagging_temperature': 78.08682242491224, 'min_data_in_leaf': 89}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.20170162310969839
Mean Absolute Error :  2.8612878716172245
R2_score :  0.7716798120869419
Adjusted R-Square:  0.7715613031808735

[I 2023-05-01 19:47:43,452] Trial 63 finished with value: 0.20368547275657597 and parameters: {'learning_rate': 0.08575235526298833, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 1.7952600379739323, 'random_strength': 6.775166992128682, 'bagging_temperature': 82.88358422341724, 'min_data_in_leaf': 56}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.20368547275657597
Mean Absolute Error :  2.879002360466976
R2_score :  0.7512370595814422
Adjusted R-Square:  0.7511079399262385

[I 2023-05-01 19:48:35,269] Trial 64 finished with value: 0.20539148641537122 and parameters: {'learning_rate': 0.08141432970949417, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.160021459526685, 'random_strength': 7.771355386522265, 'bagging_temperature': 71.79449044283481, 'min_data_in_leaf': 62}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.20539148641537122
Mean Absolute Error :  2.8394021692014464
R2_score :  0.7466390375410897
Adjusted R-Square:  0.7465075312963906

[I 2023-05-01 19:49:31,303] Trial 65 finished with value: 0.2020166191990411 and parameters: {'learning_rate': 0.07796768924702066, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.604682400280701, 'random_strength': 7.105657049788199, 'bagging_temperature': 77.46489207109204, 'min_data_in_leaf': 67}. Best is trial 52 with value: 0.1971839088035899.

Custom Error:  0.2020166191990411
Mean Absolute Error :  2.774256007238505
R2_score :  0.7917980510778454
Adjusted R-Square:  0.7916899844831495

[I 2023-05-01 19:50:28,689] Trial 66 finished with value: 0.19631948618008654 and parameters: {'learning_rate': 0.09572843012065849, 'max_depth': 9, 'n_estimators': 800, 'l2_leaf_reg': 2.8715895529960633, 'random_strength': 6.610246347501009, 'bagging_temperature': 87.5483828609188, 'min_data_in_leaf': 86}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19631948618008654
Mean Absolute Error :  2.8322266177864392
R2_score :  0.7639239983776935
Adjusted R-Square:  0.7638014638398719

[I 2023-05-01 19:51:27,928] Trial 67 finished with value: 0.2010833389607774 and parameters: {'learning_rate': 0.09539489598403898, 'max_depth': 9, 'n_estimators': 800, 'l2_leaf_reg': 3.017549028733647, 'random_strength': 6.650497058152106, 'bagging_temperature': 87.93198156768165, 'min_data_in_leaf': 85}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.2010833389607774
Mean Absolute Error :  2.8603021749933797
R2_score :  0.7628749202091205
Adjusted R-Square:  0.7627518411504343

[I 2023-05-01 19:52:33,497] Trial 68 finished with value: 0.20285128766613056 and parameters: {'learning_rate': 0.08620127032306664, 'max_depth': 8, 'n_estimators': 900, 'l2_leaf_reg': 3.6222551898330964, 'random_strength': 6.032320515672733, 'bagging_temperature': 85.7120729045817, 'min_data_in_leaf': 100}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20285128766613056
Mean Absolute Error :  2.8461495930792258
R2_score :  0.7753364149893451
Adjusted R-Square:  0.7752198040320033

[I 2023-05-01 19:53:40,355] Trial 69 finished with value: 0.20173031952242698 and parameters: {'learning_rate': 0.07240066788235602, 'max_depth': 9, 'n_estimators': 600, 'l2_leaf_reg': 2.834681301292689, 'random_strength': 8.682346916300034, 'bagging_temperature': 91.29236414262314, 'min_data_in_leaf': 96}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20173031952242698
Mean Absolute Error :  2.8335707928131457
R2_score :  0.757610088481406
Adjusted R-Square:  0.7574842767276637
Custom Error:  0.20143366616069253

[I 2023-05-01 19:54:53,018] Trial 70 finished with value: 0.20143366616069253 and parameters: {'learning_rate': 0.08233930301514422, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 4.048055801903924, 'random_strength': 7.242728722046291, 'bagging_temperature': 94.92222111575586, 'min_data_in_leaf': 78}. Best is trial 66 with value: 0.19631948618008654.

Mean Absolute Error :  2.8265655265500698
R2_score :  0.7682737624085647
Adjusted R-Square:  0.7681534856026663
Custom Error:  0.20055856607205258

[I 2023-05-01 19:56:17,019] Trial 71 finished with value: 0.20055856607205258 and parameters: {'learning_rate': 0.0905585770883796, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 2.0026614171240267, 'random_strength': 8.291645919632401, 'bagging_temperature': 81.65343714821529, 'min_data_in_leaf': 49}. Best is trial 66 with value: 0.19631948618008654.

Mean Absolute Error :  2.848160494789933
R2_score :  0.7512471096098716
Adjusted R-Square:  0.7511179951711049

[I 2023-05-01 19:57:17,049] Trial 72 finished with value: 0.20245974961594823 and parameters: {'learning_rate': 0.09462433763010862, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.330158785823188, 'random_strength': 7.634723261995555, 'bagging_temperature': 74.58129280733083, 'min_data_in_leaf': 86}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20245974961594823
Mean Absolute Error :  2.8595213141546574
R2_score :  0.7540482116689267
Adjusted R-Square:  0.7539205511337497

[I 2023-05-01 19:58:06,979] Trial 73 finished with value: 0.20367619802572787 and parameters: {'learning_rate': 0.08890314877976466, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.3220663336206426, 'random_strength': 6.619203131346467, 'bagging_temperature': 89.38886785331572, 'min_data_in_leaf': 93}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20367619802572787
Mean Absolute Error :  2.8853005236326705
R2_score :  0.7336090932341072
Adjusted R-Square:  0.7334708238360483

[I 2023-05-01 19:58:52,985] Trial 74 finished with value: 0.20567276482731822 and parameters: {'learning_rate': 0.07743591290359099, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 1.3772109071532106, 'random_strength': 8.123341019380266, 'bagging_temperature': 78.14350112373668, 'min_data_in_leaf': 76}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20567276482731822
Mean Absolute Error :  2.9932487333778384
R2_score :  0.6940460878507829
Adjusted R-Square:  0.6938872833939034

[I 2023-05-01 19:59:47,830] Trial 75 finished with value: 0.2143420069654295 and parameters: {'learning_rate': 0.09282465194754459, 'max_depth': 6, 'n_estimators': 900, 'l2_leaf_reg': 2.761890727951082, 'random_strength': 7.408490205671359, 'bagging_temperature': 85.28711735117791, 'min_data_in_leaf': 71}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.2143420069654295
Mean Absolute Error :  2.830741782713475
R2_score :  0.7734791780737499
Adjusted R-Square:  0.773361603123179

[I 2023-05-01 20:01:06,308] Trial 76 finished with value: 0.20108320150567913 and parameters: {'learning_rate': 0.09833472206127071, 'max_depth': 9, 'n_estimators': 800, 'l2_leaf_reg': 2.264856210464796, 'random_strength': 7.851092138428437, 'bagging_temperature': 81.14807485026583, 'min_data_in_leaf': 64}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20108320150567913
Mean Absolute Error :  2.882418246174661
R2_score :  0.73503864166204
Adjusted R-Square:  0.7349011142667885

[I 2023-05-01 20:02:15,654] Trial 77 finished with value: 0.20563993571533862 and parameters: {'learning_rate': 0.08553645568229655, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.1116989767620797, 'random_strength': 7.046724498112657, 'bagging_temperature': 88.94633544433574, 'min_data_in_leaf': 59}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20563993571533862
Mean Absolute Error :  2.8863267353972
R2_score :  0.753457247260735
Adjusted R-Square:  0.7533292799872613

[I 2023-05-01 20:03:06,628] Trial 78 finished with value: 0.20566070577055304 and parameters: {'learning_rate': 0.08358563410424369, 'max_depth': 9, 'n_estimators': 500, 'l2_leaf_reg': 1.713904293624036, 'random_strength': 8.55245811435463, 'bagging_temperature': 68.47075442422648, 'min_data_in_leaf': 54}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20566070577055304
Mean Absolute Error :  2.8006679556451552
R2_score :  0.7738221121921285
Adjusted R-Square:  0.7737047152404792

[I 2023-05-01 20:04:23,488] Trial 79 finished with value: 0.19790235958625135 and parameters: {'learning_rate': 0.09004393343524583, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 3.484870155275831, 'random_strength': 9.065992663749208, 'bagging_temperature': 75.48489296279573, 'min_data_in_leaf': 38}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19790235958625135
Mean Absolute Error :  2.8451276851426623
R2_score :  0.7439233212565972
Adjusted R-Square:  0.7437904054275375

[I 2023-05-01 20:05:35,490] Trial 80 finished with value: 0.20201429116853487 and parameters: {'learning_rate': 0.08895549779853683, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 3.4000552802707795, 'random_strength': 9.024052867811573, 'bagging_temperature': 96.90046169384684, 'min_data_in_leaf': 89}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20201429116853487
Mean Absolute Error :  2.8075205559161374
R2_score :  0.7804856965585788
Adjusted R-Square:  0.780371758320331

[I 2023-05-01 20:06:52,464] Trial 81 finished with value: 0.19871244220982742 and parameters: {'learning_rate': 0.09304158966074126, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.7247013052154543, 'random_strength': 9.702698534885979, 'bagging_temperature': 75.8449126394458, 'min_data_in_leaf': 37}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19871244220982742
Mean Absolute Error :  2.8497247160161208
R2_score :  0.7585772785938001
Adjusted R-Square:  0.7584519688571736

[I 2023-05-01 20:07:58,658] Trial 82 finished with value: 0.20204412056824894 and parameters: {'learning_rate': 0.07934424637167821, 'max_depth': 10, 'n_estimators': 600, 'l2_leaf_reg': 3.835067170781964, 'random_strength': 9.6486898327383, 'bagging_temperature': 75.4538407262726, 'min_data_in_leaf': 38}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20204412056824894
Mean Absolute Error :  2.8604308809344667
R2_score :  0.7493808142519958
Adjusted R-Square:  0.749250731118243

[I 2023-05-01 20:09:32,743] Trial 83 finished with value: 0.2031915269462365 and parameters: {'learning_rate': 0.0738103400426059, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.5690557602419686, 'random_strength': 9.092746391112334, 'bagging_temperature': 72.50621960752932, 'min_data_in_leaf': 29}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.2031915269462365
Mean Absolute Error :  2.828011878025563
R2_score :  0.7571127446555125
Adjusted R-Square:  0.7569866747569549

[I 2023-05-01 20:10:56,688] Trial 84 finished with value: 0.2005997142442099 and parameters: {'learning_rate': 0.09015086509402616, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.9123088032391395, 'random_strength': 9.625540384523198, 'bagging_temperature': 83.283014187502, 'min_data_in_leaf': 5}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.2005997142442099
Mean Absolute Error :  2.880978326196154
R2_score :  0.7652129553590381
Adjusted R-Square:  0.7650910898504566

[I 2023-05-01 20:11:50,157] Trial 85 finished with value: 0.20464620727117203 and parameters: {'learning_rate': 0.09981031079031402, 'max_depth': 9, 'n_estimators': 500, 'l2_leaf_reg': 4.374737543532277, 'random_strength': 9.952827587776357, 'bagging_temperature': 77.45561299361664, 'min_data_in_leaf': 21}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20464620727117203
Mean Absolute Error :  2.8288447623422006
R2_score :  0.7571269566237473
Adjusted R-Square:  0.7570008941018691

[I 2023-05-01 20:13:20,126] Trial 86 finished with value: 0.2008018003122353 and parameters: {'learning_rate': 0.0816816269342282, 'max_depth': 10, 'n_estimators': 700, 'l2_leaf_reg': 3.2079447697994743, 'random_strength': 9.483210966296086, 'bagging_temperature': 92.48946158677337, 'min_data_in_leaf': 43}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.2008018003122353
Mean Absolute Error :  2.8529347950340185
R2_score :  0.7750745729938509
Adjusted R-Square:  0.7749578261282095

[I 2023-05-01 20:14:25,371] Trial 87 finished with value: 0.20264923439450896 and parameters: {'learning_rate': 0.07606314325929163, 'max_depth': 9, 'n_estimators': 600, 'l2_leaf_reg': 3.8158854472001376, 'random_strength': 8.967168157015864, 'bagging_temperature': 75.1987318868518, 'min_data_in_leaf': 34}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.20264923439450896
Mean Absolute Error :  2.7891331750655826
R2_score :  0.7776729779457647
Adjusted R-Square:  0.77755757977439

[I 2023-05-01 20:15:38,881] Trial 88 finished with value: 0.19744563286674227 and parameters: {'learning_rate': 0.0874255777637162, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.6346705629934775, 'random_strength': 9.329868763466465, 'bagging_temperature': 70.8527230793114, 'min_data_in_leaf': 84}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19744563286674227
Mean Absolute Error :  2.8132097669871587
R2_score :  0.7578520645872739
Adjusted R-Square:  0.757726378430501

[I 2023-05-01 20:17:09,050] Trial 89 finished with value: 0.19993638806738104 and parameters: {'learning_rate': 0.08690424528852789, 'max_depth': 10, 'n_estimators': 800, 'l2_leaf_reg': 2.581949215631209, 'random_strength': 8.664733468288564, 'bagging_temperature': 66.97164428823979, 'min_data_in_leaf': 79}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19993638806738104
Mean Absolute Error :  2.7954609807383872
R2_score :  0.7720395614554125
Adjusted R-Square:  0.7719212392761706

[I 2023-05-01 20:18:36,839] Trial 90 finished with value: 0.19822168815506888 and parameters: {'learning_rate': 0.08402642465641444, 'max_depth': 10, 'n_estimators': 900, 'l2_leaf_reg': 3.4445099410867117, 'random_strength': 9.250361852765105, 'bagging_temperature': 73.2602009585212, 'min_data_in_leaf': 83}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19822168815506888
Mean Absolute Error :  2.774382861346905
R2_score :  0.7748864855349148
Adjusted R-Square:  0.7747696410430442

[I 2023-05-01 20:20:01,204] Trial 91 finished with value: 0.19635736758205652 and parameters: {'learning_rate': 0.09326330521351554, 'max_depth': 10, 'n_estimators': 900, 'l2_leaf_reg': 3.4760488778029783, 'random_strength': 9.244476309715022, 'bagging_temperature': 70.86419587640891, 'min_data_in_leaf': 84}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19635736758205652
Mean Absolute Error :  2.821870741768148
R2_score :  0.7556726954355439
Adjusted R-Square:  0.7555458780837747

[I 2023-05-01 20:21:34,405] Trial 92 finished with value: 0.2006084582281523 and parameters: {'learning_rate': 0.09323781663241729, 'max_depth': 10, 'n_estimators': 1000, 'l2_leaf_reg': 3.4937283070863074, 'random_strength': 9.27540953723414, 'bagging_temperature': 70.51362665639319, 'min_data_in_leaf': 85}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.2006084582281523
Mean Absolute Error :  2.8167547182561776
R2_score :  0.7537623288039224
Adjusted R-Square:  0.7536345198821051

[I 2023-05-01 20:22:56,491] Trial 93 finished with value: 0.19997263066867454 and parameters: {'learning_rate': 0.09654135919838623, 'max_depth': 10, 'n_estimators': 900, 'l2_leaf_reg': 3.1649700433779335, 'random_strength': 8.836810483149575, 'bagging_temperature': 72.81071926044427, 'min_data_in_leaf': 93}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.19997263066867454
Mean Absolute Error :  2.8016234722742532
R2_score :  0.7663149978674475
Adjusted R-Square:  0.7661937043707118

[I 2023-05-01 20:24:30,846] Trial 94 finished with value: 0.1988962367672154 and parameters: {'learning_rate': 0.0922397141020386, 'max_depth': 10, 'n_estimators': 900, 'l2_leaf_reg': 3.7102370637796196, 'random_strength': 9.53918327587057, 'bagging_temperature': 67.01593370301853, 'min_data_in_leaf': 83}. Best is trial 66 with value: 0.19631948618008654.

Custom Error:  0.1988962367672154
Mean Absolute Error :  2.7621463996811353
R2_score :  0.7767219777643127
Adjusted R-Square:  0.7766060859791573

[I 2023-05-01 20:25:47,999] Trial 95 finished with value: 0.19520388124404797 and parameters: {'learning_rate': 0.0880463194140946, 'max_depth': 10, 'n_estimators': 900, 'l2_leaf_reg': 3.46895420317349, 'random_strength': 9.201033706107793, 'bagging_temperature': 72.0527395552454, 'min_data_in_leaf': 87}. Best is trial 95 with value: 0.19520388124404797.

Custom Error:  0.19520388124404797
Mean Absolute Error :  2.7704881155290946
R2_score :  0.7999543020326332
Adjusted R-Square:  0.7998504689154371

[I 2023-05-01 20:27:09,965] Trial 96 finished with value: 0.19596272230780032 and parameters: {'learning_rate': 0.08410699128793042, 'max_depth': 9, 'n_estimators': 1000, 'l2_leaf_reg': 4.100138509807135, 'random_strength': 9.14704033040071, 'bagging_temperature': 62.14843017358655, 'min_data_in_leaf': 87}. Best is trial 95 with value: 0.19520388124404797.

Custom Error:  0.19596272230780032
Mean Absolute Error :  2.849986353918884
R2_score :  0.7555841455961227
Adjusted R-Square:  0.755457282282826

[I 2023-05-01 20:28:23,229] Trial 97 finished with value: 0.20220293944173257 and parameters: {'learning_rate': 0.0884720496303735, 'max_depth': 8, 'n_estimators': 1000, 'l2_leaf_reg': 4.051529416866917, 'random_strength': 8.256905028561876, 'bagging_temperature': 63.55048527415795, 'min_data_in_leaf': 87}. Best is trial 95 with value: 0.19520388124404797.

Custom Error:  0.20220293944173257
Mean Absolute Error :  2.817243503697179
R2_score :  0.7674902143176283
Adjusted R-Square:  0.7673695308134525

[I 2023-05-01 20:29:39,331] Trial 98 finished with value: 0.19993987993699366 and parameters: {'learning_rate': 0.09057142474655772, 'max_depth': 9, 'n_estimators': 1000, 'l2_leaf_reg': 3.022963912039812, 'random_strength': 8.450132124717394, 'bagging_temperature': 71.12924722409625, 'min_data_in_leaf': 91}. Best is trial 95 with value: 0.19520388124404797.

Custom Error:  0.19993987993699366
Mean Absolute Error :  2.7713882608304266
R2_score :  0.7831670326731749
Adjusted R-Square:  0.7830544861743639

[I 2023-05-01 20:30:49,509] Trial 99 finished with value: 0.19579034421778654 and parameters: {'learning_rate': 0.08564963264394657, 'max_depth': 9, 'n_estimators': 900, 'l2_leaf_reg': 2.4531148788217174, 'random_strength': 9.063137927730287, 'bagging_temperature': 62.9152158316563, 'min_data_in_leaf': 97}. Best is trial 95 with value: 0.19520388124404797.

Custom Error:  0.19579034421778654

In [85]:
good_cols = ['quantity_ordered', 'visibility', 'd_id_509', 'd_id_584', 'd_id_540',
       'd_id_648', 'd_id_7', 'd_id_410', 'd_id_1', 'd_id_643', 'd_id_684',
       'd_id_454', 'isbn_id_4595', 'isbn_id_14820', 'isbn_id_373',
       'isbn_id_31986', 'isbn_id_27825', 'isbn_id_26550', 'isbn_id_8453',
       'isbn_id_6790', 'isbn_id_19934', 'isbn_id_7865', 'row_group_ind_4',
       'row_group_ind_1', 'row_group_ind_5', 'row_group_ind_3',
       'row_group_ind_2', 'row_group_ind_6', 'row_group_ind_0',
       'row_group_ind_7', 'order_day', 'delivered_day', 'order_month_cos',
       'order_dayofweek_sin', 'order_dayofweek_cos', 'delivered_dayofweek_sin',
       'delivered_dayofweek_cos']

"""Uncomment for tuning the model"""
import optuna
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.svm import SVR

imp_features = ['quantity_ordered', 'quantity_submitted', 'order_delivery_days', 'd_id_509', 'd_id_584', 'd_id_540', 'd_id_648', 'd_id_410', 'row_group_ind_6']


def run(trial):

    xtrain =df_train[good_cols].copy()
    xvalid = df_test[good_cols].copy()
    y_train = df_train['quantity_received']
    y_test = df_test['quantity_received']


    xtrain[good_cols] = qt.fit_transform(xtrain[good_cols])
    xvalid[good_cols] = qt.transform(xvalid[good_cols])

    # Define the hyperparameters to be tuned
    params = {
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 0.1),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, 100),
        'l2_leaf_reg': trial.suggest_float('l2_leaf_reg', 0.1, 10.0),
        'random_strength': trial.suggest_float('random_strength', 1e-9, 10.0),
        'bagging_temperature': trial.suggest_float('bagging_temperature', 0.01, 100.0),
        'min_data_in_leaf': trial.suggest_int('min_data_in_leaf', 1, 100),

        # 'learning_rate': trial.suggest_loguniform('learning_rate', low=0.01, high=0.5),
        # 'depth': trial.suggest_int('depth', 3, 10),
        # 'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', low=1e-5, high=1e-1),
        # 'bagging_temperature': trial.suggest_loguniform('bagging_temperature', low=0.01, high=100.0),
        # 'random_strength': trial.suggest_loguniform('random_strength', low=1e-5, high=1e-1),
        # 'od_type': 'Iter',
        # 'od_wait': 50,
        # 'loss_function': 'MAE'
    }

    # Create the SVR model with the given hyperparameters
    # Train model with current hyperparameters
    model = CatBoostRegressor(**params, loss_function='MAE')
    # model.fit(X_train, y_train)
    model.fit(xtrain, y_train, verbose=False)
    preds_valid = model.predict(xvalid)
    mae_ = mean_absolute_error(y_test, preds_valid)
    r2_sc = r2_score(y_test, preds_valid)

    temp = df_test.copy()
    temp['preds'] = model.predict(xvalid)

    print("Mean Absolute Error : ", mae_)
    print("R2_score : ", r2_sc)
    r2 = r2_sc.copy()
    n = len(y_test)
    p = xvalid.shape[1]  # number of features in X
    adj_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
    print("Adjusted R-Square: ", adj_r2)

    
    final_error = new_metric(temp)
    print("Custom Error: ",final_error)
    del temp
    return final_error

study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=100)

# study.best_params

[I 2023-05-01 20:30:50,300] A new study created in memory with name: no-name-7a1a0569-4b4c-43a5-95bb-d17d5144c1ee
[W 2023-05-01 20:30:50,327] Trial 0 failed with parameters: {} because of the following error: KeyError("['isbn_id_4595', 'isbn_id_14820', 'isbn_id_373', 'isbn_id_31986', 'isbn_id_27825', 'isbn_id_26550', 'isbn_id_8453', 'isbn_id_6790', 'isbn_id_19934', 'isbn_id_7865'] not in index").
Traceback (most recent call last):
  File "c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\nshre\AppData\Local\Temp\ipykernel_13204\2953264376.py", line 22, in run
    xtrain =df_train[good_cols].copy()
  File "c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\pandas\core\frame.py", line 3766, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\pandas\core\indexes\base.py", line 5876, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\pandas\core\indexes\base.py", line 5938, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['isbn_id_4595', 'isbn_id_14820', 'isbn_id_373', 'isbn_id_31986', 'isbn_id_27825', 'isbn_id_26550', 'isbn_id_8453', 'isbn_id_6790', 'isbn_id_19934', 'isbn_id_7865'] not in index"
[W 2023-05-01 20:30:50,381] Trial 0 failed with value None.

KeyError: "['isbn_id_4595', 'isbn_id_14820', 'isbn_id_373', 'isbn_id_31986', 'isbn_id_27825', 'isbn_id_26550', 'isbn_id_8453', 'isbn_id_6790', 'isbn_id_19934', 'isbn_id_7865'] not in index"

In [14]:
112792/259287, 146495/259287

(0.435008311253553, 0.564991688746447)

In [15]:
# How long does order usually take to deliver?
X_train['order_delivery_days'] = (X_train['evsd'] - X_train['order_date']).dt.days
X_valid['order_delivery_days'] = (X_valid['evsd'] - X_valid['order_date']).dt.days

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\3015875561.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_delivery_days'] = (X_train['evsd'] - X_train['order_date']).dt.days
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\3015875561.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_delivery_days'] = (X_valid['evsd'] - X_valid['order_date']).dt.days

In [16]:
# Define a funtion to peform one hot encoding for the top 10 most frequent categories of Categorical Features
def one_hot_top10(df,feature,top10_categories):
    for category in top10_categories:
        df[feature+'_'+category]=np.where(df[feature]==category,1,0)

In [17]:
"""
Create a dict for the top 10 most frequent categories of Categorical Features
Call the function to perform one hot encoding on Categorical Features
verify the train and test set after applying one hot encoding for the Categorical 
"""

var_dict_train ={}

for col in ['d_id', 'isbn_id']:
  var_dict_train[col] = [x for x in X_train[col].value_counts().sort_values(ascending=False).head(10).index]


display(var_dict_train)

{'d_id': ['509', '584', '540', '648', '410', '7', '1', '643', '454', '110'],
 'isbn_id': ['4595',
  '26550',
  '27825',
  '14820',
  '19934',
  '29771',
  '7865',
  '31986',
  '6790',
  '8453']}

In [18]:
for key,val in var_dict_train.items():
  one_hot_top10(X_train,key,val)

for key,val in var_dict_train.items():
  one_hot_top10(X_valid,key,val)

display(X_train.head())
display(X_valid.head())

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453
2,1,JFK2,648,16750,11165,2022-09-30,2022-10-03,AFT Lite,6,6,6,1,2,train,JFK2_648_16750_11165 ...,3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1,JFK2,648,16750,27008,2022-10-14,2022-10-17,AFT Lite,6,6,6,2,2,train,JFK2_648_16750_27008 ...,3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1,JFK2,584,29062,62664,2022-10-17,2022-10-19,AFT Lite,12,12,12,5,1,train,JFK2_584_29062_62664 ...,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1,JFK2,393,24754,91483,2022-10-19,2022-10-28,AFT Lite,16,16,16,7,6,train,JFK2_393_24754_91483 ...,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,1,JFK2,7,27826,175768,2022-10-11,2022-10-12,AFT Lite,24,24,24,5,1,train,JFK2_7_27826_175768 ...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train,JFK2_540_30718_67271 ...,12,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train,JFK2_540_30718_125389 ...,11,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1,JFK2,7,8748,33598,2022-11-15,2022-11-16,AFT Lite,8,8,8,1,1,train,JFK2_7_8748_33598 _2...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,1,JFK2,7,8748,142228,2022-11-01,2022-11-02,AFT Lite,16,16,16,3,1,train,JFK2_7_8748_142228 _...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1,JFK2,7,8748,27330,2022-11-05,2022-11-06,AFT Lite,0,24,0,6,1,train,JFK2_7_8748_27330 _2...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [19]:
X_train['po_source_ind_AFT_Lite'] = np.where(X_train['po_source_ind'] == 'AFT Lite', 1, 0)
X_valid['po_source_ind_AFT_Lite'] = np.where(X_valid['po_source_ind'] == 'AFT Lite', 1, 0)

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\180782182.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['po_source_ind_AFT_Lite'] = np.where(X_train['po_source_ind'] == 'AFT Lite', 1, 0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\180782182.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['po_source_ind_AFT_Lite'] = np.where(X_valid['po_source_ind'] == 'AFT Lite', 1, 0)

In [20]:
X_train['row_group_ind'] = X_train['row_group_ind'].astype(str)
var_dict_train_ ={}

for col in ['row_group_ind']:
  var_dict_train_[col] = [x for x in X_train[col].value_counts().sort_values(ascending=False).index]


display(var_dict_train_)

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\3238755345.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['row_group_ind'] = X_train['row_group_ind'].astype(str)

{'row_group_ind': ['4', '1', '5', '3', '2', '6', '0', '7']}

In [21]:
for key,val in var_dict_train_.items():
  one_hot_top10(X_train,key,val)

for key,val in var_dict_train_.items():
  one_hot_top10(X_valid,key,val)

display(X_train.head())
display(X_valid.head())

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2297884223.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature+'_'+category]=np.where(df[feature]==category,1,0)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453,po_source_ind_AFT_Lite,row_group_ind_4,row_group_ind_1,row_group_ind_5,row_group_ind_3,row_group_ind_2,row_group_ind_6,row_group_ind_0,row_group_ind_7
2,1,JFK2,648,16750,11165,2022-09-30,2022-10-03,AFT Lite,6,6,6,1,2,train,JFK2_648_16750_11165 ...,3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0
3,1,JFK2,648,16750,27008,2022-10-14,2022-10-17,AFT Lite,6,6,6,2,2,train,JFK2_648_16750_27008 ...,3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0
8,1,JFK2,584,29062,62664,2022-10-17,2022-10-19,AFT Lite,12,12,12,5,1,train,JFK2_584_29062_62664 ...,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0
9,1,JFK2,393,24754,91483,2022-10-19,2022-10-28,AFT Lite,16,16,16,7,6,train,JFK2_393_24754_91483 ...,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1
11,1,JFK2,7,27826,175768,2022-10-11,2022-10-12,AFT Lite,24,24,24,5,1,train,JFK2_7_27826_175768 ...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453,po_source_ind_AFT_Lite,row_group_ind_4,row_group_ind_1,row_group_ind_5,row_group_ind_3,row_group_ind_2,row_group_ind_6,row_group_ind_0,row_group_ind_7
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train,JFK2_540_30718_67271 ...,12,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train,JFK2_540_30718_125389 ...,11,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,1,JFK2,7,8748,33598,2022-11-15,2022-11-16,AFT Lite,8,8,8,1,1,train,JFK2_7_8748_33598 _2...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
5,1,JFK2,7,8748,142228,2022-11-01,2022-11-02,AFT Lite,16,16,16,3,1,train,JFK2_7_8748_142228 _...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
6,1,JFK2,7,8748,27330,2022-11-05,2022-11-06,AFT Lite,0,24,0,6,1,train,JFK2_7_8748_27330 _2...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [23]:

X_train['order_day'] = X_train['order_date'].dt.day
X_train['order_dayofweek'] = X_train['order_date'].dt.dayofweek
X_train['order_dayofyear'] = X_train['order_date'].dt.dayofyear
X_train['order_month'] = X_train['order_date'].dt.month

X_train['delivered_day'] = X_train['evsd'].dt.day
X_train['delivered_dayofweek'] = X_train['evsd'].dt.dayofweek
X_train['delivered_dayofyear'] = X_train['evsd'].dt.dayofyear
X_train['delivered_month'] = X_train['evsd'].dt.month

X_train['order_month_sin'] = np.sin(2 * np.pi * X_train['order_month'] / 12)
X_train['order_month_cos'] = np.cos(2 * np.pi * X_train['order_month'] / 12)

X_train['order_dayofweek_sin'] = np.sin(2 * np.pi * X_train['order_dayofweek'] / 7)
X_train['order_dayofweek_cos'] = np.cos(2 * np.pi * X_train['order_dayofweek'] / 7)

X_train['delivered_month_sin'] = np.sin(2 * np.pi * X_train['delivered_month'] / 12)
X_train['delivered_month_cos'] = np.cos(2 * np.pi * X_train['delivered_month'] / 12)

X_train['delivered_dayofweek_sin'] = np.sin(2 * np.pi * X_train['delivered_dayofweek'] / 7)
X_train['delivered_dayofweek_cos'] = np.cos(2 * np.pi * X_train['delivered_dayofweek'] / 7)

X_train.drop(['order_month','delivered_month'], axis =1, inplace = True)
display(X_train.head())


X_valid['order_day'] = X_valid['order_date'].dt.day
X_valid['order_dayofweek'] = X_valid['order_date'].dt.dayofweek
X_valid['order_dayofyear'] = X_valid['order_date'].dt.dayofyear
X_valid['order_month'] = X_valid['order_date'].dt.month

X_valid['delivered_day'] = X_valid['evsd'].dt.day
X_valid['delivered_dayofweek'] = X_valid['evsd'].dt.dayofweek
X_valid['delivered_dayofyear'] = X_valid['evsd'].dt.dayofyear
X_valid['delivered_month'] = X_valid['evsd'].dt.month

X_valid['order_month_sin'] = np.sin(2 * np.pi * X_valid['order_month'] / 12)
X_valid['order_month_cos'] = np.cos(2 * np.pi * X_valid['order_month'] / 12)

X_valid['order_dayofweek_sin'] = np.sin(2 * np.pi * X_valid['order_dayofweek'] / 7)
X_valid['order_dayofweek_cos'] = np.cos(2 * np.pi * X_valid['order_dayofweek'] / 7)

X_valid['delivered_month_sin'] = np.sin(2 * np.pi * X_valid['delivered_month'] / 12)
X_valid['delivered_month_cos'] = np.cos(2 * np.pi * X_valid['delivered_month'] / 12)

X_valid['delivered_dayofweek_sin'] = np.sin(2 * np.pi * X_valid['delivered_dayofweek'] / 7)
X_valid['delivered_dayofweek_cos'] = np.cos(2 * np.pi * X_valid['delivered_dayofweek'] / 7)

X_valid.drop(['order_month','delivered_month'], axis =1, inplace = True)
display(X_valid.head())

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_day'] = X_train['order_date'].dt.day
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_dayofweek'] = X_train['order_date'].dt.dayofweek
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_dayofyear'] = X_train['order_date'].dt.dayofyear
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_month'] = X_train['order_date'].dt.month
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_day'] = X_train['evsd'].dt.day
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_dayofweek'] = X_train['evsd'].dt.dayofweek
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_dayofyear'] = X_train['evsd'].dt.dayofyear
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_month'] = X_train['evsd'].dt.month
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_month_sin'] = np.sin(2 * np.pi * X_train['order_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_month_cos'] = np.cos(2 * np.pi * X_train['order_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_dayofweek_sin'] = np.sin(2 * np.pi * X_train['order_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['order_dayofweek_cos'] = np.cos(2 * np.pi * X_train['order_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_month_sin'] = np.sin(2 * np.pi * X_train['delivered_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_month_cos'] = np.cos(2 * np.pi * X_train['delivered_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_dayofweek_sin'] = np.sin(2 * np.pi * X_train['delivered_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['delivered_dayofweek_cos'] = np.cos(2 * np.pi * X_train['delivered_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train.drop(['order_month','delivered_month'], axis =1, inplace = True)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453,po_source_ind_AFT_Lite,row_group_ind_4,row_group_ind_1,row_group_ind_5,row_group_ind_3,row_group_ind_2,row_group_ind_6,row_group_ind_0,row_group_ind_7,order_day,order_dayofweek,order_dayofyear,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos
2,1,JFK2,648,16750,11165,2022-09-30,2022-10-03,AFT Lite,6,6,6,1,2,train,JFK2_648_16750_11165 ...,3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,30,4,273,3,0,276,-1.000000,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.5,0.000000,1.000000
3,1,JFK2,648,16750,27008,2022-10-14,2022-10-17,AFT Lite,6,6,6,2,2,train,JFK2_648_16750_27008 ...,3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,14,4,287,17,0,290,-0.866025,5.000000e-01,-0.433884,-0.900969,-0.866025,0.5,0.000000,1.000000
8,1,JFK2,584,29062,62664,2022-10-17,2022-10-19,AFT Lite,12,12,12,5,1,train,JFK2_584_29062_62664 ...,2,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,17,0,290,19,2,292,-0.866025,5.000000e-01,0.000000,1.000000,-0.866025,0.5,0.974928,-0.222521
9,1,JFK2,393,24754,91483,2022-10-19,2022-10-28,AFT Lite,16,16,16,7,6,train,JFK2_393_24754_91483 ...,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,19,2,292,28,4,301,-0.866025,5.000000e-01,0.974928,-0.222521,-0.866025,0.5,-0.433884,-0.900969
11,1,JFK2,7,27826,175768,2022-10-11,2022-10-12,AFT Lite,24,24,24,5,1,train,JFK2_7_27826_175768 ...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,11,1,284,12,2,285,-0.866025,5.000000e-01,0.781831,0.623490,-0.866025,0.5,0.974928,-0.222521

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_day'] = X_valid['order_date'].dt.day
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_dayofweek'] = X_valid['order_date'].dt.dayofweek
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_dayofyear'] = X_valid['order_date'].dt.dayofyear
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_month'] = X_valid['order_date'].dt.month
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_day'] = X_valid['evsd'].dt.day
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_dayofweek'] = X_valid['evsd'].dt.dayofweek
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_dayofyear'] = X_valid['evsd'].dt.dayofyear
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_month'] = X_valid['evsd'].dt.month
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_month_sin'] = np.sin(2 * np.pi * X_valid['order_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_month_cos'] = np.cos(2 * np.pi * X_valid['order_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_dayofweek_sin'] = np.sin(2 * np.pi * X_valid['order_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['order_dayofweek_cos'] = np.cos(2 * np.pi * X_valid['order_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_month_sin'] = np.sin(2 * np.pi * X_valid['delivered_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_month_cos'] = np.cos(2 * np.pi * X_valid['delivered_month'] / 12)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_dayofweek_sin'] = np.sin(2 * np.pi * X_valid['delivered_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['delivered_dayofweek_cos'] = np.cos(2 * np.pi * X_valid['delivered_dayofweek'] / 7)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2288242729.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid.drop(['order_month','delivered_month'], axis =1, inplace = True)

,region_id,warehouse_id,d_id,isbn_id,order_id,order_date,evsd,po_source_ind,quantity_ordered,quantity_submitted,quantity_received,row_group_ind,visibility,tag,unique_id,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453,po_source_ind_AFT_Lite,row_group_ind_4,row_group_ind_1,row_group_ind_5,row_group_ind_3,row_group_ind_2,row_group_ind_6,row_group_ind_0,row_group_ind_7,order_day,order_dayofweek,order_dayofyear,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos
0,1,JFK2,540,30718,67271,2022-11-02,2022-11-14,AFT Lite,54,54,54,4,9,train,JFK2_540_30718_67271 ...,12,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,2,2,306,14,0,318,-0.5,0.866025,0.974928,-0.222521,-5.000000e-01,0.866025,0.000000,1.000000
1,1,JFK2,540,30718,125389,2022-11-20,2022-12-01,AFT Lite,60,60,60,5,3,train,JFK2_540_30718_125389 ...,11,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,20,6,324,1,3,335,-0.5,0.866025,-0.781831,0.623490,-2.449294e-16,1.000000,0.433884,-0.900969
4,1,JFK2,7,8748,33598,2022-11-15,2022-11-16,AFT Lite,8,8,8,1,1,train,JFK2_7_8748_33598 _2...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,15,1,319,16,2,320,-0.5,0.866025,0.781831,0.623490,-5.000000e-01,0.866025,0.974928,-0.222521
5,1,JFK2,7,8748,142228,2022-11-01,2022-11-02,AFT Lite,16,16,16,3,1,train,JFK2_7_8748_142228 _...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,305,2,2,306,-0.5,0.866025,0.781831,0.623490,-5.000000e-01,0.866025,0.974928,-0.222521
6,1,JFK2,7,8748,27330,2022-11-05,2022-11-06,AFT Lite,0,24,0,6,1,train,JFK2_7_8748_27330 _2...,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,5,5,309,6,6,310,-0.5,0.866025,-0.974928,-0.222521,-5.000000e-01,0.866025,-0.781831,0.623490

In [24]:
req_cols = [col for col in X_train.columns if col not in ['region_id', 'warehouse_id', 'd_id', 'isbn_id', 'order_id', 'order_date', 'evsd', 'po_source_ind', 'tag', 'unique_id', 'row_group_ind','quantity_received']]

In [ ]:
def mae(y_true, predictions):
    y_true, predictions = np.array(y_true), np.array(predictions)
    return np.mean(np.abs(y_true - predictions))

In [46]:
def new_metric(df):
    df['mae'] = df[['quantity_received', 'preds']].apply(lambda row: mae(row['quantity_received'], row['preds']), axis=1)
    final_error = df['mae'].sum()/ df['preds'].sum()
    return final_error

In [47]:
xtrain =X_train[req_cols].copy()
xvalid = X_valid[req_cols].copy()
y_train = X_train['quantity_received']
y_test = X_valid['quantity_received']


xtrain[req_cols] = qt.fit_transform(xtrain[req_cols])
xvalid[req_cols] = qt.transform(xvalid[req_cols])

# Create a Random Forest Regressor model with the hyperparameters
# rf_model = RandomForestRegressor(n_estimators=30,random_state=42)
# rf_model.fit(xtrain, y_train)
X_valid['preds'] = rf_model.predict(xvalid)
mae_ = mean_absolute_error(y_test, X_valid['preds'])
r2_sc = r2_score(y_test, X_valid['preds'])
print("Mean Absolute Error : ", mae_)
print("R2_score : ", r2_sc)
r2 = r2_sc.copy()
n = len(y_test)
p = xvalid.shape[1]  # number of features in X
adj_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
print("Adjusted R-Square: ", adj_r2)
final_error = new_metric(X_valid)
print(final_error)

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\3137132013.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_valid['preds'] = rf_model.predict(xvalid)

Mean Absolute Error :  5.434794445068843
R2_score :  0.5378839752506729
Adjusted R-Square:  0.5376913312681708
0.4168225344250589

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\56918459.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mae'] = df[['quantity_received', 'preds']].apply(lambda row: mae(row['quantity_received'], row['preds']), axis=1)

In [51]:
"""Uncomment for tuning the model"""
import optuna
from sklearn.metrics import mean_absolute_error, r2_score

imp_features = ['quantity_ordered', 'quantity_submitted', 'order_delivery_days', 'd_id_509', 'd_id_584', 'd_id_540', 'd_id_648', 'd_id_410', 'row_group_ind_6']


def run(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-3, 0.1)
    reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
    reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
    subsample = trial.suggest_float("subsample", 0.1, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.1, 1.0)
    max_depth = trial.suggest_int("max_depth", 3, 6)
    n_estimators = trial.suggest_int("n_estimators", 20, 3000)

    xtrain =X_train[req_cols].copy()
    xvalid = X_valid[req_cols].copy()
    y_train = X_train['quantity_received']
    y_test = X_valid['quantity_received']


    xtrain[req_cols] = qt.fit_transform(xtrain[req_cols])
    xvalid[req_cols] = qt.transform(xvalid[req_cols])

    model = xgb.XGBRegressor(
            random_state=42,
            objective='reg:squarederror',
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            reg_lambda=reg_lambda,
            reg_alpha=reg_alpha,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            max_depth=max_depth,
            eval_metric='mae'
        )
    model.fit(xtrain, y_train)
    preds_valid = model.predict(xvalid)
    mae_ = mean_absolute_error(y_test, preds_valid)
    r2_sc = r2_score(y_test, preds_valid)

    temp = X_valid.copy()
    temp['preds'] = model.predict(xvalid)

    print("Mean Absolute Error : ", mae_)
    print("R2_score : ", r2_sc)
    r2 = r2_sc.copy()
    n = len(y_test)
    p = xvalid.shape[1]  # number of features in X
    adj_r2 = 1 - ((1 - r2) * (n - 1)) / (n - p - 1)
    print("Adjusted R-Square: ", adj_r2)

    
    final_error = new_metric(temp)
    print("Custom Error: ",final_error)
    del temp
    return final_error

study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=100)

# study.best_params

[I 2023-05-01 13:48:55,777] A new study created in memory with name: no-name-a9808f54-a1b3-400d-aece-81ae7c6687d8
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  4.964312758831197
R2_score :  0.5572387838956188
Adjusted R-Square:  0.5570542084223615

[I 2023-05-01 13:49:48,670] Trial 0 finished with value: 0.3573869003998817 and parameters: {'learning_rate': 0.024062633584525494, 'reg_lambda': 0.5302322775357684, 'reg_alpha': 1.0779420377638884e-07, 'subsample': 0.8472258033819929, 'colsample_bytree': 0.30810152442768746, 'max_depth': 3, 'n_estimators': 800}. Best is trial 0 with value: 0.3573869003998817.

Custom Error:  0.3573869003998817

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  6.09391848363381
R2_score :  0.5299794465679821
Adjusted R-Square:  0.5297835073959525

[I 2023-05-01 13:53:49,284] Trial 1 finished with value: 0.5068525325148309 and parameters: {'learning_rate': 0.0904248285415048, 'reg_lambda': 0.0018170377343215845, 'reg_alpha': 0.0010324660697566533, 'subsample': 0.6697210022842387, 'colsample_bytree': 0.7059416382478167, 'max_depth': 3, 'n_estimators': 2887}. Best is trial 0 with value: 0.3573869003998817.

Custom Error:  0.5068525325148309

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  6.74444393201544
R2_score :  0.5650217076701751
Adjusted R-Square:  0.5648403766925665

[I 2023-05-01 13:58:09,826] Trial 2 finished with value: 0.6582624199679276 and parameters: {'learning_rate': 0.08920830403904134, 'reg_lambda': 0.004142147394071729, 'reg_alpha': 18.21996645352845, 'subsample': 0.6095302871129272, 'colsample_bytree': 0.9890190231282137, 'max_depth': 4, 'n_estimators': 2013}. Best is trial 0 with value: 0.3573869003998817.

Custom Error:  0.6582624199679276

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  4.76007629613642
R2_score :  0.5700158651476742
Adjusted R-Square:  0.5698366161025981

[I 2023-05-01 13:59:33,978] Trial 3 finished with value: 0.3483896670895734 and parameters: {'learning_rate': 0.023952788490740496, 'reg_lambda': 37.12676499257691, 'reg_alpha': 0.0358975763328946, 'subsample': 0.2659879274701461, 'colsample_bytree': 0.9529758803123948, 'max_depth': 4, 'n_estimators': 742}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  0.3483896670895734

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  5.234946018134578
R2_score :  0.5713572890713696
Adjusted R-Square:  0.5711785992305476
Custom Error:  0.3958777860167141

[I 2023-05-01 14:02:46,859] Trial 4 finished with value: 0.3958777860167141 and parameters: {'learning_rate': 0.04722767485302928, 'reg_lambda': 0.12719808525966947, 'reg_alpha': 1.555331700817579e-05, 'subsample': 0.5149020916377237, 'colsample_bytree': 0.3200770059681363, 'max_depth': 4, 'n_estimators': 2209}. Best is trial 3 with value: 0.3483896670895734.
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  5.340407179289597
R2_score :  0.5572926114749797
Adjusted R-Square:  0.5571080584410206

[I 2023-05-01 14:04:47,320] Trial 5 finished with value: 0.40624637199121705 and parameters: {'learning_rate': 0.061681101316608054, 'reg_lambda': 0.03105900704747869, 'reg_alpha': 0.028431148977773622, 'subsample': 0.7092099784217432, 'colsample_bytree': 0.888726104659897, 'max_depth': 3, 'n_estimators': 1364}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  0.40624637199121705

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  5.19091352803167
R2_score :  0.5589188758817649
Adjusted R-Square:  0.5587350007945446

[I 2023-05-01 14:07:19,496] Trial 6 finished with value: 0.3821256660130852 and parameters: {'learning_rate': 0.05979209370712706, 'reg_lambda': 10.786107894370621, 'reg_alpha': 9.415635664116319e-06, 'subsample': 0.2786391652250664, 'colsample_bytree': 0.30522766153349284, 'max_depth': 5, 'n_estimators': 1579}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  0.3821256660130852

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  10.870123332308086
R2_score :  0.1336721222061592
Adjusted R-Square:  0.133310972963128

[I 2023-05-01 14:07:40,092] Trial 7 finished with value: 2.386974187282933 and parameters: {'learning_rate': 0.0057710382758350744, 'reg_lambda': 2.2260140536130257e-06, 'reg_alpha': 16.96581422035373, 'subsample': 0.6163984453904692, 'colsample_bytree': 0.262412610426475, 'max_depth': 4, 'n_estimators': 62}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  2.386974187282933

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  6.0453092101524994
R2_score :  0.5630939872432007
Adjusted R-Square:  0.5629118526497894

[I 2023-05-01 14:08:39,573] Trial 8 finished with value: 0.5199596312777377 and parameters: {'learning_rate': 0.08707979066808078, 'reg_lambda': 4.041909525410783e-08, 'reg_alpha': 0.002539043886967415, 'subsample': 0.4340919697531098, 'colsample_bytree': 0.3449031358694457, 'max_depth': 5, 'n_estimators': 488}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  0.5199596312777377

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  6.270326134070927
R2_score :  0.5764214610994849
Adjusted R-Square:  0.5762448823784148

[I 2023-05-01 14:13:34,518] Trial 9 finished with value: 0.5757100729772554 and parameters: {'learning_rate': 0.044207392984355984, 'reg_lambda': 12.76031302702067, 'reg_alpha': 2.116605105415951e-07, 'subsample': 0.8801026152001282, 'colsample_bytree': 0.9592071841271801, 'max_depth': 5, 'n_estimators': 1944}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  0.5757100729772554

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  5.315109669664407
R2_score :  0.6553098955356806
Adjusted R-Square:  0.6551662033222607

[I 2023-05-01 14:15:16,040] Trial 10 finished with value: 0.41660645889913756 and parameters: {'learning_rate': 0.005749366059862596, 'reg_lambda': 68.14519453360327, 'reg_alpha': 0.20458707383013697, 'subsample': 0.11250183813246833, 'colsample_bytree': 0.6290788961693439, 'max_depth': 6, 'n_estimators': 880}. Best is trial 3 with value: 0.3483896670895734.

Custom Error:  0.41660645889913756

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  4.763972011797978
R2_score :  0.55926754508776
Adjusted R-Square:  0.5590838153515356

[I 2023-05-01 14:16:35,187] Trial 11 finished with value: 0.33370860604031266 and parameters: {'learning_rate': 0.026370622863200733, 'reg_lambda': 0.48554912850024223, 'reg_alpha': 1.0560845150552289e-08, 'subsample': 0.9164113346673944, 'colsample_bytree': 0.46337144199173924, 'max_depth': 3, 'n_estimators': 860}. Best is trial 11 with value: 0.33370860604031266.

Custom Error:  0.33370860604031266

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  4.829311333701944
R2_score :  0.5561039827409697
Adjusted R-Square:  0.5559189341990414

[I 2023-05-01 14:17:46,822] Trial 12 finished with value: 0.3308215215591815 and parameters: {'learning_rate': 0.022509709404237223, 'reg_lambda': 1.3095786572755257, 'reg_alpha': 1.3006897484528176e-05, 'subsample': 0.9814969313580326, 'colsample_bytree': 0.5093717921834616, 'max_depth': 3, 'n_estimators': 1095}. Best is trial 12 with value: 0.3308215215591815.

Custom Error:  0.3308215215591815

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  4.847312129489326
R2_score :  0.5690103481748295
Adjusted R-Square:  0.5688306799562477

[I 2023-05-01 14:19:17,446] Trial 13 finished with value: 0.34283550117195877 and parameters: {'learning_rate': 0.02618618600514947, 'reg_lambda': 0.44505412614070766, 'reg_alpha': 4.306973833221766e-08, 'subsample': 0.9819856157298377, 'colsample_bytree': 0.48001305948311745, 'max_depth': 3, 'n_estimators': 1264}. Best is trial 12 with value: 0.3308215215591815.

Custom Error:  0.34283550117195877

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

Mean Absolute Error :  8.086189996715099
R2_score :  0.5904484191049821
Adjusted R-Square:  0.5902776878527464

[I 2023-05-01 14:19:32,740] Trial 14 finished with value: 0.5902752095260586 and parameters: {'learning_rate': 0.034469783971417804, 'reg_lambda': 3.927185868219017e-05, 'reg_alpha': 1.1666654873146806e-08, 'subsample': 0.993024498146316, 'colsample_bytree': 0.12770484309335528, 'max_depth': 3, 'n_estimators': 95}. Best is trial 12 with value: 0.3308215215591815.

Custom Error:  0.5902752095260586

C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:10: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12864\2791605496.py:11: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

In [54]:

X = X_train[req_cols].copy()
y = X_train['quantity_received'].copy()
X[req_cols] = qt.fit_transform(X[req_cols])
X[req_cols].head()

,quantity_ordered,quantity_submitted,quantity_received,visibility,order_delivery_days,d_id_509,d_id_584,d_id_540,d_id_648,d_id_410,d_id_7,d_id_1,d_id_643,d_id_454,d_id_110,isbn_id_4595,isbn_id_26550,isbn_id_27825,isbn_id_14820,isbn_id_19934,isbn_id_29771,isbn_id_7865,isbn_id_31986,isbn_id_6790,isbn_id_8453,po_source_ind_AFT_Lite,row_group_ind_4,row_group_ind_1,row_group_ind_5,row_group_ind_3,row_group_ind_2,row_group_ind_6,row_group_ind_0,row_group_ind_7
2,0.368368,0.256757,0.455956,0.579079,0.633133,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.368368,0.256757,0.455956,0.579079,0.633133,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,0.661662,0.609610,0.705706,0.000000,0.316316,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9,0.792292,0.770771,0.814815,0.912412,0.863864,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11,0.864865,0.851351,0.881882,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day'] = df['order_date'].dt.day
df['order_dayofweek'] = df['order_date'].dt.dayofweek
df['order_dayofyear'] = df['order_date'].dt.dayofyear

df['delivered_year'] = df['evsd'].dt.year
df['delivered_month'] = df['evsd'].dt.month
df['delivered_day'] = df['evsd'].dt.day
df['delivered_dayofweek'] = df['evsd'].dt.dayofweek
df['delivered_dayofyear'] = df['evsd'].dt.dayofyear

In [20]:
df['order_month_sin'] = np.sin(2 * np.pi * df['order_month'] / 12)
df['order_month_cos'] = np.cos(2 * np.pi * df['order_month'] / 12)

df['order_dayofweek_sin'] = np.sin(2 * np.pi * df['order_dayofweek'] / 7)
df['order_dayofweek_cos'] = np.cos(2 * np.pi * df['order_dayofweek'] / 7)

df['delivered_month_sin'] = np.sin(2 * np.pi * df['delivered_month'] / 12)
df['delivered_month_cos'] = np.cos(2 * np.pi * df['delivered_month'] / 12)

df['delivered_dayofweek_sin'] = np.sin(2 * np.pi * df['delivered_dayofweek'] / 7)
df['delivered_dayofweek_cos'] = np.cos(2 * np.pi * df['delivered_dayofweek'] / 7)

df.head()

,LOCATION,d_id,isbn_id,order_id_1,order_date,evsd,row_group_ind,visibility,quantity_ordered,quantity_submitted,quantity_received,tag,order_delivery_days,order_year,order_month,order_day,order_dayofweek,order_dayofyear,delivered_year,delivered_month,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos
0,JFK2,1,25556,3912,2022-09-30,2022-10-04,7.0,2.0,4.0,4.0,4,train,4,2022,9,30,4,273,2022,10,4,1,277,-1.000000,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490
1,JFK2,1,25556,91302,2022-11-16,2022-11-19,4.0,1.0,20.0,20.0,20,train,3,2022,11,16,2,320,2022,11,19,5,323,-0.500000,8.660254e-01,0.974928,-0.222521,-0.500000,0.866025,-0.974928,-0.222521
2,JFK2,1,33083,26096,2022-10-07,2022-10-11,4.0,4.0,4.0,4.0,4,train,4,2022,10,7,4,280,2022,10,11,1,284,-0.866025,5.000000e-01,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490
3,JFK2,1,33083,138855,2022-10-19,2022-10-22,5.0,2.0,4.0,4.0,4,train,3,2022,10,19,2,292,2022,10,22,5,295,-0.866025,5.000000e-01,0.974928,-0.222521,-0.866025,0.500000,-0.974928,-0.222521
4,JFK2,1,33083,114502,2022-10-18,2022-10-21,6.0,1.0,4.0,4.0,4,train,3,2022,10,18,1,291,2022,10,21,4,294,-0.866025,5.000000e-01,0.781831,0.623490,-0.866025,0.500000,-0.433884,-0.900969

In [21]:
# As categorical variable
df['order_month_season'] = df['order_date'].dt.month.map({1: 'winter', 2: 'winter', 3: 'spring', 4: 'spring', 5: 'spring', 6: 'summer', 7: 'summer', 8: 'summer', 9: 'fall', 10: 'fall', 11: 'fall', 12: 'winter'})
df['delivered_month_season'] = df['evsd'].dt.month.map({1: 'winter', 2: 'winter', 3: 'spring', 4: 'spring', 5: 'spring', 6: 'summer', 7: 'summer', 8: 'summer', 9: 'fall', 10: 'fall', 11: 'fall', 12: 'winter'})

# As continuous variable using sine and cosine transformations
df['order_month_sin'] = np.sin(2 * np.pi * df['order_month'] / 12)
df['order_month_cos'] = np.cos(2 * np.pi * df['order_month'] / 12)
df['delivered_month_sin'] = np.sin(2 * np.pi * df['delivered_month'] / 12)
df['delivered_month_cos'] = np.cos(2 * np.pi * df['delivered_month'] / 12)
df.head()

,LOCATION,d_id,isbn_id,order_id_1,order_date,evsd,row_group_ind,visibility,quantity_ordered,quantity_submitted,quantity_received,tag,order_delivery_days,order_year,order_month,order_day,order_dayofweek,order_dayofyear,delivered_year,delivered_month,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos,order_month_season,delivered_month_season
0,JFK2,1,25556,3912,2022-09-30,2022-10-04,7.0,2.0,4.0,4.0,4,train,4,2022,9,30,4,273,2022,10,4,1,277,-1.000000,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall
1,JFK2,1,25556,91302,2022-11-16,2022-11-19,4.0,1.0,20.0,20.0,20,train,3,2022,11,16,2,320,2022,11,19,5,323,-0.500000,8.660254e-01,0.974928,-0.222521,-0.500000,0.866025,-0.974928,-0.222521,fall,fall
2,JFK2,1,33083,26096,2022-10-07,2022-10-11,4.0,4.0,4.0,4.0,4,train,4,2022,10,7,4,280,2022,10,11,1,284,-0.866025,5.000000e-01,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall
3,JFK2,1,33083,138855,2022-10-19,2022-10-22,5.0,2.0,4.0,4.0,4,train,3,2022,10,19,2,292,2022,10,22,5,295,-0.866025,5.000000e-01,0.974928,-0.222521,-0.866025,0.500000,-0.974928,-0.222521,fall,fall
4,JFK2,1,33083,114502,2022-10-18,2022-10-21,6.0,1.0,4.0,4.0,4,train,3,2022,10,18,1,291,2022,10,21,4,294,-0.866025,5.000000e-01,0.781831,0.623490,-0.866025,0.500000,-0.433884,-0.900969,fall,fall

In [22]:
df['order_weekday'] = (df['order_dayofweek'] < 5).astype(int)  # 0 for weekend, 1 for weekday
df['delivered_weekday'] = (df['delivered_dayofweek'] < 5).astype(int)

In [23]:
df.shape

(357596, 35)

In [24]:
(df['d_id'] + df['isbn_id']).nunique()

10878

In [25]:
(df['d_id'] +'__' + df['isbn_id']).value_counts(dropna = False, normalize = True).head(50)
# Remaining you put as unknown

540__4595     0.001158
524__26550    0.001124
410__24163    0.001119
540__373      0.001116
540__14820    0.001116
410__29416    0.001116
524__7865     0.001102
410__10204    0.001096
524__29771    0.001077
410__19394    0.001077
410__1528     0.001077
524__8453     0.001071
410__28311    0.001057
410__2081     0.001054
410__28446    0.001054
410__13646    0.001054
524__27825    0.001051
524__21625    0.001049
410__26105    0.001043
540__31986    0.001032
524__6790     0.001026
524__19934    0.001024
410__32365    0.001018
410__8551     0.001018
410__17481    0.001012
410__30418    0.000998
410__5310     0.000998
410__31291    0.000979
410__12868    0.000976
410__28595    0.000973
410__1108     0.000970
410__6998     0.000956
410__4002     0.000954
540__29918    0.000948
540__24090    0.000948
524__30821    0.000948
540__15727    0.000948
540__9338     0.000948
540__2044     0.000942
540__15592    0.000937
410__30967    0.000937
410__20003    0.000937
524__20309    0.000937
540__23917    0.000937
540__3935     0.000937
540__24747    0.000937
540__13418    0.000937
540__7468     0.000937
540__10228    0.000937
540__2547     0.000937
Name: proportion, dtype: float64

In [26]:
df['isbn_id'].value_counts(dropna = False, normalize = True).head(10)

isbn_id
4595     0.001158
26550    0.001124
24163    0.001119
373      0.001116
14820    0.001116
29416    0.001116
7865     0.001102
10204    0.001096
29771    0.001077
19394    0.001077
Name: proportion, dtype: float64

In [27]:
df['d_id'].value_counts(dropna = False, normalize = True)

d_id
509    0.382574
584    0.123184
540    0.094204
648    0.060823
7      0.047584
410    0.045951
1      0.042819
643    0.021091
684    0.019609
454    0.019226
110    0.017995
639    0.015613
174    0.014419
524    0.014391
652    0.013622
18     0.008901
136    0.008266
393    0.007525
566    0.007192
472    0.006689
763    0.006502
343    0.005271
218    0.004899
711    0.003591
13     0.001913
302    0.001326
373    0.001270
830    0.001054
440    0.000453
79     0.000419
613    0.000411
216    0.000313
845    0.000277
701    0.000235
127    0.000204
746    0.000067
803    0.000056
462    0.000039
210    0.000017
241    0.000006
Name: proportion, dtype: float64

In [28]:
df.nunique()

LOCATION                      1
d_id                         40
isbn_id                    9492
order_id_1                 1993
order_date                  110
evsd                        106
row_group_ind                 8
visibility                   25
quantity_ordered            218
quantity_submitted          230
quantity_received           264
tag                           2
order_delivery_days          23
order_year                    1
order_month                   4
order_day                    31
order_dayofweek               7
order_dayofyear             110
delivered_year                2
delivered_month               5
delivered_day                31
delivered_dayofweek           7
delivered_dayofyear         106
order_month_sin               4
order_month_cos               4
order_dayofweek_sin           7
order_dayofweek_cos           7
delivered_month_sin           5
delivered_month_cos           5
delivered_dayofweek_sin       7
delivered_dayofweek_cos       7
order_month_season            2
delivered_month_season        2
order_weekday                 2
delivered_weekday             2
dtype: int64

In [29]:
# Create a new column that combines the values of the existing columns
df['unique_id'] = df.apply(lambda row: f"{row['LOCATION']}_{row['d_id']}_{row['isbn_id']}_{row['order_id_1']}", axis=1)

# Drop duplicates based on the new column
df_unique = df.drop_duplicates(subset=['unique_id'])

df_unique.shape, df.shape

((142773, 36), (357596, 36))

In [30]:
print(df_unique.shape)
df_unique.head()

(142773, 36)

,LOCATION,d_id,isbn_id,order_id_1,order_date,evsd,row_group_ind,visibility,quantity_ordered,quantity_submitted,quantity_received,tag,order_delivery_days,order_year,order_month,order_day,order_dayofweek,order_dayofyear,delivered_year,delivered_month,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos,order_month_season,delivered_month_season,order_weekday,delivered_weekday,unique_id
0,JFK2,1,25556,3912,2022-09-30,2022-10-04,7.0,2.0,4.0,4.0,4,train,4,2022,9,30,4,273,2022,10,4,1,277,-1.000000,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall,1,1,JFK2_1_25556_3912
1,JFK2,1,25556,91302,2022-11-16,2022-11-19,4.0,1.0,20.0,20.0,20,train,3,2022,11,16,2,320,2022,11,19,5,323,-0.500000,8.660254e-01,0.974928,-0.222521,-0.500000,0.866025,-0.974928,-0.222521,fall,fall,1,0,JFK2_1_25556_91302
2,JFK2,1,33083,26096,2022-10-07,2022-10-11,4.0,4.0,4.0,4.0,4,train,4,2022,10,7,4,280,2022,10,11,1,284,-0.866025,5.000000e-01,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall,1,1,JFK2_1_33083_26096
3,JFK2,1,33083,138855,2022-10-19,2022-10-22,5.0,2.0,4.0,4.0,4,train,3,2022,10,19,2,292,2022,10,22,5,295,-0.866025,5.000000e-01,0.974928,-0.222521,-0.866025,0.500000,-0.974928,-0.222521,fall,fall,1,0,JFK2_1_33083_138855
4,JFK2,1,33083,114502,2022-10-18,2022-10-21,6.0,1.0,4.0,4.0,4,train,3,2022,10,18,1,291,2022,10,21,4,294,-0.866025,5.000000e-01,0.781831,0.623490,-0.866025,0.500000,-0.433884,-0.900969,fall,fall,1,1,JFK2_1_33083_114502

In [31]:
df.columns

Index(['LOCATION', 'd_id', 'isbn_id', 'order_id_1', 'order_date', 'evsd',
       'row_group_ind', 'visibility', 'quantity_ordered', 'quantity_submitted',
       'quantity_received', 'tag', 'order_delivery_days', 'order_year',
       'order_month', 'order_day', 'order_dayofweek', 'order_dayofyear',
       'delivered_year', 'delivered_month', 'delivered_day',
       'delivered_dayofweek', 'delivered_dayofyear', 'order_month_sin',
       'order_month_cos', 'order_dayofweek_sin', 'order_dayofweek_cos',
       'delivered_month_sin', 'delivered_month_cos', 'delivered_dayofweek_sin',
       'delivered_dayofweek_cos', 'order_month_season',
       'delivered_month_season', 'order_weekday', 'delivered_weekday',
       'unique_id'],
      dtype='object')

In [32]:
df[['d_id', 'isbn_id', 'order_id_1', 'order_date', 'evsd', 'row_group_ind']].dtypes

d_id                     object
isbn_id                  object
order_id_1               object
order_date       datetime64[ns]
evsd             datetime64[ns]
row_group_ind           float64
dtype: object

In [33]:
df['row_group_ind'] = df['row_group_ind'].astype(str)

In [34]:
df.columns

Index(['LOCATION', 'd_id', 'isbn_id', 'order_id_1', 'order_date', 'evsd',
       'row_group_ind', 'visibility', 'quantity_ordered', 'quantity_submitted',
       'quantity_received', 'tag', 'order_delivery_days', 'order_year',
       'order_month', 'order_day', 'order_dayofweek', 'order_dayofyear',
       'delivered_year', 'delivered_month', 'delivered_day',
       'delivered_dayofweek', 'delivered_dayofyear', 'order_month_sin',
       'order_month_cos', 'order_dayofweek_sin', 'order_dayofweek_cos',
       'delivered_month_sin', 'delivered_month_cos', 'delivered_dayofweek_sin',
       'delivered_dayofweek_cos', 'order_month_season',
       'delivered_month_season', 'order_weekday', 'delivered_weekday',
       'unique_id'],
      dtype='object')

In [37]:
df.drop(['order_date_VC', 'evsd_VC'], axis =1, inplace = True)

In [38]:
for col in ['d_id', 'isbn_id', 'order_id_1',  'row_group_ind', 'order_month_season', 'delivered_month_season']:
    temp_dict = dict(df[col].value_counts(normalize = True))
    df[f'{col}_VC'] = df[col].map(temp_dict)
    del temp_dict

In [41]:
req_cols = [col for col in df.columns if col not in ['LOCATION', 'order_date', 'evsd', 'd_id', 
                                                     'isbn_id', 'order_id_1','quantity_received', 'tag',
                                                      'order_date', 'evsd', 'row_group_ind', 'unique_id','target', 
                                                      'delivered_year', 'order_year',  'order_month_season',
                                                        'delivered_month_season', 'order_month', 'delivered_month']]

In [42]:
df[req_cols].head(1)

,visibility,quantity_ordered,quantity_submitted,order_delivery_days,order_day,order_dayofweek,order_dayofyear,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos,order_weekday,delivered_weekday,d_id_VC,isbn_id_VC,order_id_1_VC,row_group_ind_VC,order_month_season_VC,delivered_month_season_VC
0,2.0,4.0,4.0,4,30,4,273,4,1,277,-1.0,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.5,0.781831,0.62349,1,1,0.042819,0.000506,0.000895,0.124056,0.725084,0.680735

In [43]:
df['order_month_season'].value_counts(dropna = False)

order_month_season
fall      259287
winter     98309
Name: count, dtype: int64

In [44]:
df.head()

,LOCATION,d_id,isbn_id,order_id_1,order_date,evsd,row_group_ind,visibility,quantity_ordered,quantity_submitted,quantity_received,tag,order_delivery_days,order_year,order_month,order_day,order_dayofweek,order_dayofyear,delivered_year,delivered_month,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos,order_month_season,delivered_month_season,order_weekday,delivered_weekday,unique_id,d_id_VC,isbn_id_VC,order_id_1_VC,row_group_ind_VC,order_month_season_VC,delivered_month_season_VC
0,JFK2,1,25556,3912,2022-09-30,2022-10-04,7.0,2.0,4.0,4.0,4,train,4,2022,9,30,4,273,2022,10,4,1,277,-1.000000,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall,1,1,JFK2_1_25556_3912,0.042819,0.000506,0.000895,0.124056,0.725084,0.680735
1,JFK2,1,25556,91302,2022-11-16,2022-11-19,4.0,1.0,20.0,20.0,20,train,3,2022,11,16,2,320,2022,11,19,5,323,-0.500000,8.660254e-01,0.974928,-0.222521,-0.500000,0.866025,-0.974928,-0.222521,fall,fall,1,0,JFK2_1_25556_91302,0.042819,0.000506,0.000604,0.125460,0.725084,0.680735
2,JFK2,1,33083,26096,2022-10-07,2022-10-11,4.0,4.0,4.0,4.0,4,train,4,2022,10,7,4,280,2022,10,11,1,284,-0.866025,5.000000e-01,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall,1,1,JFK2_1_33083_26096,0.042819,0.000350,0.000940,0.125460,0.725084,0.680735
3,JFK2,1,33083,138855,2022-10-19,2022-10-22,5.0,2.0,4.0,4.0,4,train,3,2022,10,19,2,292,2022,10,22,5,295,-0.866025,5.000000e-01,0.974928,-0.222521,-0.866025,0.500000,-0.974928,-0.222521,fall,fall,1,0,JFK2_1_33083_138855,0.042819,0.000350,0.000738,0.125169,0.725084,0.680735
4,JFK2,1,33083,114502,2022-10-18,2022-10-21,6.0,1.0,4.0,4.0,4,train,3,2022,10,18,1,291,2022,10,21,4,294,-0.866025,5.000000e-01,0.781831,0.623490,-0.866025,0.500000,-0.433884,-0.900969,fall,fall,1,1,JFK2_1_33083_114502,0.042819,0.000350,0.000721,0.124764,0.725084,0.680735

In [45]:
from sklearn.preprocessing import QuantileTransformer

# Instantiate the transformer
qt = QuantileTransformer(output_distribution='uniform')

In [46]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import PoissonRegressor, LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score
import xgboost as xgb

# Split data into features and target
X = df[req_cols]
y = df['quantity_received']

# Split data into train and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = df[df['tag'] == 'train'][req_cols].copy()
X_test = df[df['tag'] == 'test'][req_cols].copy()
y_train = df[df['tag'] == 'train']['quantity_received']
y_test = df[df['tag'] == 'test']['quantity_received']


X_train = qt.fit_transform(X_train)
X_test = qt.transform(X_test)

# Train Poisson regression model
# Define XGBoost model parameters
params = {'learning_rate': 0.09494445071749025, 'reg_lambda': 0.12153018654604152, 'reg_alpha': 0.002926293135127233, 
          'subsample': 0.4759168036681104, 'colsample_bytree': 0.23668139727995788, 'max_depth': 5, 
          'n_estimators': 926}


# {
#     'objective': 'reg:squarederror',
#     'learning_rate': 0.1,
#     'max_depth': 6,
#     'min_child_weight': 1,
#     'gamma': 0,
#     'subsample': 0.8,
#     'colsample_bytree': 0.8,
#     'n_estimators': 100
# }
model = xgb.XGBRegressor(**params, 
            random_state=42,
            objective='reg:squarederror',
            eval_metric='mae')
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Evaluate model performance on test set
mae = mean_absolute_error(y_test, y_pred)
score = r2_score(y_test, y_pred)
print(f'Mean absolute error: {mae:.4f}')
print(f'Score: {score:.4f}')

Mean absolute error: 4.8610
Score: 0.7694

## Score all Data

In [47]:
df_scored = df.copy()
print(df_scored.shape)
df_scored.head()

(357596, 42)

,LOCATION,d_id,isbn_id,order_id_1,order_date,evsd,row_group_ind,visibility,quantity_ordered,quantity_submitted,quantity_received,tag,order_delivery_days,order_year,order_month,order_day,order_dayofweek,order_dayofyear,delivered_year,delivered_month,delivered_day,delivered_dayofweek,delivered_dayofyear,order_month_sin,order_month_cos,order_dayofweek_sin,order_dayofweek_cos,delivered_month_sin,delivered_month_cos,delivered_dayofweek_sin,delivered_dayofweek_cos,order_month_season,delivered_month_season,order_weekday,delivered_weekday,unique_id,d_id_VC,isbn_id_VC,order_id_1_VC,row_group_ind_VC,order_month_season_VC,delivered_month_season_VC
0,JFK2,1,25556,3912,2022-09-30,2022-10-04,7.0,2.0,4.0,4.0,4,train,4,2022,9,30,4,273,2022,10,4,1,277,-1.000000,-1.836970e-16,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall,1,1,JFK2_1_25556_3912,0.042819,0.000506,0.000895,0.124056,0.725084,0.680735
1,JFK2,1,25556,91302,2022-11-16,2022-11-19,4.0,1.0,20.0,20.0,20,train,3,2022,11,16,2,320,2022,11,19,5,323,-0.500000,8.660254e-01,0.974928,-0.222521,-0.500000,0.866025,-0.974928,-0.222521,fall,fall,1,0,JFK2_1_25556_91302,0.042819,0.000506,0.000604,0.125460,0.725084,0.680735
2,JFK2,1,33083,26096,2022-10-07,2022-10-11,4.0,4.0,4.0,4.0,4,train,4,2022,10,7,4,280,2022,10,11,1,284,-0.866025,5.000000e-01,-0.433884,-0.900969,-0.866025,0.500000,0.781831,0.623490,fall,fall,1,1,JFK2_1_33083_26096,0.042819,0.000350,0.000940,0.125460,0.725084,0.680735
3,JFK2,1,33083,138855,2022-10-19,2022-10-22,5.0,2.0,4.0,4.0,4,train,3,2022,10,19,2,292,2022,10,22,5,295,-0.866025,5.000000e-01,0.974928,-0.222521,-0.866025,0.500000,-0.974928,-0.222521,fall,fall,1,0,JFK2_1_33083_138855,0.042819,0.000350,0.000738,0.125169,0.725084,0.680735
4,JFK2,1,33083,114502,2022-10-18,2022-10-21,6.0,1.0,4.0,4.0,4,train,3,2022,10,18,1,291,2022,10,21,4,294,-0.866025,5.000000e-01,0.781831,0.623490,-0.866025,0.500000,-0.433884,-0.900969,fall,fall,1,1,JFK2_1_33083_114502,0.042819,0.000350,0.000721,0.124764,0.725084,0.680735

In [40]:
# df['order_year'].value_counts(dropna = False)


"""
MAE : < 2.5
"""


[['year', 'month', 'day', 'delivered_dayofyear', ]]

# [['order_dayofweek']]

order_year
2022    357596
Name: count, dtype: int64

In [39]:
dict(df['row_group_ind'].value_counts(dropna= False, normalize = True))

{'1.0': 0.12554111343527333,
 '4.0': 0.12546001633127887,
 '2.0': 0.12540129084217944,
 '5.0': 0.1251691853376436,
 '3.0': 0.1249678408035884,
 '6.0': 0.12476369981767134,
 '0.0': 0.12464065593574872,
 '7.0': 0.1240561974966163}

In [ ]:
df_new['row_group_ind'].map()

In [48]:
df_scored[req_cols]  = qt.transform(df_scored[req_cols])
df_scored['predicted_orders'] = model.predict(df_scored[req_cols])
df_scored[['quantity_received', 'predicted_orders']]

        quantity_received  predicted_orders
0                       4          2.189799
1                      20         20.220161
2                       4          2.500038
3                       4          4.191618
4                       4          4.620018
...                   ...               ...
357591                  8          9.290109
357592                 12         11.229070
357593                132        126.057327
357594                 24         29.560225
357595                  6          4.305933

[357596 rows x 2 columns]

In [51]:
mae = mean_absolute_error(df_scored['quantity_received'], df_scored['predicted_orders'])
score = r2_score(df_scored['quantity_received'], df_scored['predicted_orders'])
print(f'Mean absolute error: {mae:.4f}')
print(f'Score: {score:.4f}')

Mean absolute error: 3.2349
Score: 0.8917

In [49]:
df_scored['quantity_received'].describe()

count    357596.000000
mean         13.113701
std          27.279292
min           0.000000
25%           0.000000
50%           6.000000
75%          12.000000
max        1650.000000
Name: quantity_received, dtype: float64

In [50]:
df_scored['predicted_orders'].describe()

count    357596.000000
mean         13.112150
std          25.541054
min         -39.842880
25%           3.075947
50%           7.475512
75%          12.033930
max         790.471252
Name: predicted_orders, dtype: float64

## Hypertuning

In [96]:
"""Uncomment for tuning the model"""
import optuna
def run(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-3, 0.1)
    reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
    reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
    subsample = trial.suggest_float("subsample", 0.1, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.1, 1.0)
    max_depth = trial.suggest_int("max_depth", 3, 6)
    n_estimators = trial.suggest_int("n_estimators", 20, 3000)


    model = xgb.XGBRegressor(
            random_state=42,
            objective='reg:squarederror',
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            reg_lambda=reg_lambda,
            reg_alpha=reg_alpha,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            max_depth=max_depth,
            eval_metric='mae'
        )
    model.fit(X_train, y_train)
    preds_valid = model.predict(X_test)
    mae_ = mean_absolute_error(y_test, preds_valid)
    r2_sc = r2_score(y_test, preds_valid)
    print("Mean Absolute Error : ", mae_)
    print("R2_score : ", r2_sc)
    return mae_

study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=20)

# study.best_params

[I 2023-04-28 08:27:37,198] A new study created in memory with name: no-name-6633f2c9-b973-4c05-879d-a6a88d4adc0f
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:30:51,858] Trial 0 finished with value: 5.30203999121291 and parameters: {'learning_rate': 0.03309359543919969, 'reg_lambda': 0.2159147341660498, 'reg_alpha': 0.06916918029376977, 'subsample': 0.5038536182347256, 'colsample_bytree': 0.3266281397228815, 'max_depth': 5, 'n_estimators': 2820}. Best is trial 0 with value: 5.30203999121291.

Mean Absolute Error :  5.30203999121291
R2_score :  0.7478631424634002

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:31:44,537] Trial 1 finished with value: 6.824564105550033 and parameters: {'learning_rate': 0.09494445071749025, 'reg_lambda': 0.12153018654604152, 'reg_alpha': 0.002926293135127233, 'subsample': 0.4759168036681104, 'colsample_bytree': 0.23668139727995788, 'max_depth': 5, 'n_estimators': 926}. Best is trial 0 with value: 5.30203999121291.

Mean Absolute Error :  6.824564105550033
R2_score :  0.7252528819371045

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:32:14,441] Trial 2 finished with value: 5.085238951615853 and parameters: {'learning_rate': 0.08539001075999679, 'reg_lambda': 0.0017116086819376096, 'reg_alpha': 9.733517229448778e-07, 'subsample': 0.8486752491235564, 'colsample_bytree': 0.765683289497556, 'max_depth': 6, 'n_estimators': 302}. Best is trial 2 with value: 5.085238951615853.

Mean Absolute Error :  5.085238951615853
R2_score :  0.6582640974257273

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:34:36,542] Trial 3 finished with value: 4.316466609593959 and parameters: {'learning_rate': 0.06002410622268421, 'reg_lambda': 0.9102659582342552, 'reg_alpha': 0.00019889251192707353, 'subsample': 0.3447540708103442, 'colsample_bytree': 0.644771781552105, 'max_depth': 3, 'n_estimators': 2362}. Best is trial 3 with value: 4.316466609593959.

Mean Absolute Error :  4.316466609593959
R2_score :  0.7345140742866197

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:36:29,075] Trial 4 finished with value: 4.014516335495757 and parameters: {'learning_rate': 0.029709652164319054, 'reg_lambda': 6.140086141171898, 'reg_alpha': 0.019604127340872607, 'subsample': 0.25246008848760754, 'colsample_bytree': 0.7080422852270917, 'max_depth': 4, 'n_estimators': 1433}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.014516335495757
R2_score :  0.7506425492580595

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:41:06,670] Trial 5 finished with value: 4.8431481285810944 and parameters: {'learning_rate': 0.06534568249655477, 'reg_lambda': 1.3336415440754149e-05, 'reg_alpha': 0.000345415372188516, 'subsample': 0.844978725545569, 'colsample_bytree': 0.44989422418684, 'max_depth': 6, 'n_estimators': 2945}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.8431481285810944
R2_score :  0.7186509266666582

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:43:14,007] Trial 6 finished with value: 4.817154102344354 and parameters: {'learning_rate': 0.05297263382164796, 'reg_lambda': 0.0009063555368964637, 'reg_alpha': 1.2798673223114063e-08, 'subsample': 0.35112507992555586, 'colsample_bytree': 0.6116591007571499, 'max_depth': 3, 'n_estimators': 1879}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.817154102344354
R2_score :  0.7055969828412461

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:47:33,274] Trial 7 finished with value: 4.788554937946665 and parameters: {'learning_rate': 0.017752000591089934, 'reg_lambda': 2.710613584367079e-06, 'reg_alpha': 2.4821573039019524, 'subsample': 0.29862823089860413, 'colsample_bytree': 0.3345167048863346, 'max_depth': 6, 'n_estimators': 2080}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.788554937946665
R2_score :  0.7591261342754274

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:49:55,215] Trial 8 finished with value: 4.065070158728204 and parameters: {'learning_rate': 0.029324035728187696, 'reg_lambda': 0.6438178323500426, 'reg_alpha': 0.0821740082898111, 'subsample': 0.14134871330258492, 'colsample_bytree': 0.8295613348742853, 'max_depth': 3, 'n_estimators': 2301}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.065070158728204
R2_score :  0.7233241158947401

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:50:37,802] Trial 9 finished with value: 6.206847562617861 and parameters: {'learning_rate': 0.077082421202773, 'reg_lambda': 0.053731762413557996, 'reg_alpha': 0.008959806512862106, 'subsample': 0.12998078892517306, 'colsample_bytree': 0.1113762572136053, 'max_depth': 6, 'n_estimators': 898}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  6.206847562617861
R2_score :  0.7392738976386494

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:52:23,091] Trial 10 finished with value: 5.448784966336275 and parameters: {'learning_rate': 0.001683717177778158, 'reg_lambda': 55.502350347799705, 'reg_alpha': 49.42282137256974, 'subsample': 0.6723973732262163, 'colsample_bytree': 0.9949414623192445, 'max_depth': 4, 'n_estimators': 1275}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  5.448784966336275
R2_score :  0.6797171374340709

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:54:08,304] Trial 11 finished with value: 4.085750954056798 and parameters: {'learning_rate': 0.03542790877442886, 'reg_lambda': 41.25654627199507, 'reg_alpha': 0.4560511887435661, 'subsample': 0.147532038106214, 'colsample_bytree': 0.815671183841725, 'max_depth': 4, 'n_estimators': 1836}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.085750954056798
R2_score :  0.7594484502850081

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:55:09,808] Trial 12 finished with value: 4.254570276865067 and parameters: {'learning_rate': 0.03513889075361243, 'reg_lambda': 5.924322568326093, 'reg_alpha': 0.1128754407699121, 'subsample': 0.10981470118206949, 'colsample_bytree': 0.7705293464848719, 'max_depth': 3, 'n_estimators': 1440}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.254570276865067
R2_score :  0.7572186240389522

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:57:49,328] Trial 13 finished with value: 4.791194169543509 and parameters: {'learning_rate': 0.025010535957519203, 'reg_lambda': 6.824506512475626e-08, 'reg_alpha': 10.570979534990876, 'subsample': 0.22461807089542404, 'colsample_bytree': 0.9158758279999428, 'max_depth': 4, 'n_estimators': 2496}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.791194169543509
R2_score :  0.6846157907626407

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:58:36,173] Trial 14 finished with value: 4.3047275109652485 and parameters: {'learning_rate': 0.045580208679295006, 'reg_lambda': 4.269465720292161, 'reg_alpha': 95.5353225451274, 'subsample': 0.2490420291766568, 'colsample_bytree': 0.6795898624820328, 'max_depth': 3, 'n_estimators': 989}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.3047275109652485
R2_score :  0.7616933575832009

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 08:58:48,379] Trial 15 finished with value: 4.995289434156859 and parameters: {'learning_rate': 0.014966719408486352, 'reg_lambda': 0.015391094671520136, 'reg_alpha': 1.2413569766336248, 'subsample': 0.3809086949632191, 'colsample_bytree': 0.533610399214107, 'max_depth': 4, 'n_estimators': 204}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.995289434156859
R2_score :  0.7495774682087979

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:00:52,979] Trial 16 finished with value: 4.243051719462243 and parameters: {'learning_rate': 0.04593885265112103, 'reg_lambda': 88.0882031076654, 'reg_alpha': 0.009811285188130726, 'subsample': 0.20974407775230022, 'colsample_bytree': 0.875570296468998, 'max_depth': 5, 'n_estimators': 1673}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.243051719462243
R2_score :  0.7392742644368074

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:03:06,459] Trial 17 finished with value: 4.093689252968496 and parameters: {'learning_rate': 0.024155222458682596, 'reg_lambda': 2.301706730001585, 'reg_alpha': 4.662088877381834e-05, 'subsample': 0.40407323084066116, 'colsample_bytree': 0.731074366583236, 'max_depth': 3, 'n_estimators': 2229}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  4.093689252968496
R2_score :  0.7476057198864594

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:03:40,280] Trial 18 finished with value: 9.070102359674655 and parameters: {'learning_rate': 0.0012930917356519175, 'reg_lambda': 0.4013732538033482, 'reg_alpha': 0.055953531181059404, 'subsample': 0.25423058984118274, 'colsample_bytree': 0.8662101703697235, 'max_depth': 4, 'n_estimators': 529}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  9.070102359674655
R2_score :  0.44163328405924074

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\3012480772.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:04:29,924] Trial 19 finished with value: 5.430407336248827 and parameters: {'learning_rate': 0.04153763734194716, 'reg_lambda': 0.013079948726058456, 'reg_alpha': 0.9995965435106116, 'subsample': 0.11164312307294227, 'colsample_bytree': 0.5426943298548812, 'max_depth': 3, 'n_estimators': 1308}. Best is trial 4 with value: 4.014516335495757.

Mean Absolute Error :  5.430407336248827
R2_score :  0.7386240109592743

In [97]:
"""Uncomment for tuning the model"""
import optuna
def run(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-3, 0.1)
    reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
    reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
    subsample = trial.suggest_float("subsample", 0.1, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.1, 1.0)
    max_depth = trial.suggest_int("max_depth", 3, 6)
    n_estimators = trial.suggest_int("n_estimators", 20, 3000)


    model = xgb.XGBRegressor(
            random_state=42,
            objective='reg:squarederror',
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            reg_lambda=reg_lambda,
            reg_alpha=reg_alpha,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            max_depth=max_depth,
            eval_metric='mae'
        )
    model.fit(X_train, y_train)
    preds_valid = model.predict(X_test)
    mae_ = mean_absolute_error(y_test, preds_valid)
    r2_sc = r2_score(y_test, preds_valid)
    print("Mean Absolute Error : ", mae_)
    print("R2_score : ", r2_sc)
    return mae_

study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=100)

# study.best_params

[I 2023-04-28 09:04:30,128] A new study created in memory with name: no-name-0d3aee4a-db2a-445a-aee6-6a631401074b
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:04:41,170] Trial 0 finished with value: 4.45109362412442 and parameters: {'learning_rate': 0.07511926391905335, 'reg_lambda': 9.155477788500397, 'reg_alpha': 2.0220448757521527e-06, 'subsample': 0.485471495251942, 'colsample_bytree': 0.2838175433464417, 'max_depth': 3, 'n_estimators': 260}. Best is trial 0 with value: 4.45109362412442.

Mean Absolute Error :  4.45109362412442
R2_score :  0.7820779441828376

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:04:51,238] Trial 1 finished with value: 4.37555884175738 and parameters: {'learning_rate': 0.09352998540410909, 'reg_lambda': 0.00036642843752606705, 'reg_alpha': 0.4009758857433482, 'subsample': 0.6332212397539065, 'colsample_bytree': 0.524477195640949, 'max_depth': 3, 'n_estimators': 192}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.37555884175738
R2_score :  0.7225718959237353

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:06:12,419] Trial 2 finished with value: 4.6421249747019795 and parameters: {'learning_rate': 0.08751711247805773, 'reg_lambda': 8.926641410419766, 'reg_alpha': 4.097168185791003e-08, 'subsample': 0.821061008835693, 'colsample_bytree': 0.12700196394387855, 'max_depth': 3, 'n_estimators': 2335}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.6421249747019795
R2_score :  0.7665492732905539

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:08:14,493] Trial 3 finished with value: 4.419209723726743 and parameters: {'learning_rate': 0.03145172256075458, 'reg_lambda': 4.999706038464734e-05, 'reg_alpha': 60.774996801999954, 'subsample': 0.551267338326362, 'colsample_bytree': 0.5609709595493059, 'max_depth': 5, 'n_estimators': 1537}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.419209723726743
R2_score :  0.7323315937345198

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:11:07,241] Trial 4 finished with value: 4.543365449905182 and parameters: {'learning_rate': 0.09888878048825313, 'reg_lambda': 24.855488205229097, 'reg_alpha': 0.5834662929754639, 'subsample': 0.9802581610602823, 'colsample_bytree': 0.5554147201309242, 'max_depth': 3, 'n_estimators': 2672}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.543365449905182
R2_score :  0.7398357016519148

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:13:38,257] Trial 5 finished with value: 5.357332845560095 and parameters: {'learning_rate': 0.06625231145468774, 'reg_lambda': 8.848086435644778e-07, 'reg_alpha': 1.9862217971987475e-07, 'subsample': 0.5544800717464493, 'colsample_bytree': 0.2980344126396455, 'max_depth': 4, 'n_estimators': 1767}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.357332845560095
R2_score :  0.7420422338459665

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:16:51,756] Trial 6 finished with value: 5.1697740533867504 and parameters: {'learning_rate': 0.08370992322094004, 'reg_lambda': 0.006482423000071544, 'reg_alpha': 7.607417108993234e-08, 'subsample': 0.47335763912093665, 'colsample_bytree': 0.5491432977090945, 'max_depth': 6, 'n_estimators': 1628}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.1697740533867504
R2_score :  0.7181880729554668

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:20:16,777] Trial 7 finished with value: 4.399734740061761 and parameters: {'learning_rate': 0.019277007954551645, 'reg_lambda': 3.7228712122524425e-05, 'reg_alpha': 1.5096281335986974e-07, 'subsample': 0.9714907644671561, 'colsample_bytree': 0.44359452647471065, 'max_depth': 5, 'n_estimators': 2662}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.399734740061761
R2_score :  0.7243442076497664

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 09:23:11,825] Trial 8 finished with value: 5.623420045858467 and parameters: {'learning_rate': 0.09363933420622975, 'reg_lambda': 2.215876134372027e-08, 'reg_alpha': 1.9828507172812145e-08, 'subsample': 0.53214042829062, 'colsample_bytree': 0.6078857109761135, 'max_depth': 3, 'n_estimators': 2867}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.623420045858467
R2_score :  0.6709702157996298

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 20:57:38,146] Trial 9 finished with value: 4.78350110575384 and parameters: {'learning_rate': 0.023361361840033373, 'reg_lambda': 2.6842680948509104e-08, 'reg_alpha': 2.174301431738352e-06, 'subsample': 0.5837255176982205, 'colsample_bytree': 0.6572166118349376, 'max_depth': 5, 'n_estimators': 2868}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.78350110575384
R2_score :  0.66309180139157

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 20:57:42,148] Trial 10 finished with value: 4.963308442169709 and parameters: {'learning_rate': 0.055280297416579895, 'reg_lambda': 0.010017499383590443, 'reg_alpha': 0.0075379566623527666, 'subsample': 0.23734176895651116, 'colsample_bytree': 0.839702589285737, 'max_depth': 4, 'n_estimators': 48}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.963308442169709
R2_score :  0.7128506477516869

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 20:59:29,658] Trial 11 finished with value: 5.141923206292742 and parameters: {'learning_rate': 0.0029367987349087354, 'reg_lambda': 0.00017443901378252373, 'reg_alpha': 0.0008930028522699851, 'subsample': 0.9999053622380785, 'colsample_bytree': 0.36904344791808086, 'max_depth': 6, 'n_estimators': 1099}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.141923206292742
R2_score :  0.7497472931596717

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:01:05,343] Trial 12 finished with value: 4.667377574193389 and parameters: {'learning_rate': 0.04733416631341617, 'reg_lambda': 9.448236366700265e-06, 'reg_alpha': 0.0001951386840519026, 'subsample': 0.7233303225789511, 'colsample_bytree': 0.42905839112183586, 'max_depth': 5, 'n_estimators': 915}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.667377574193389
R2_score :  0.7467026265693292

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:05:26,624] Trial 13 finished with value: 5.8964317790871545 and parameters: {'learning_rate': 0.0643927278916192, 'reg_lambda': 0.0013307672342664915, 'reg_alpha': 0.020823809558739532, 'subsample': 0.8356682139085756, 'colsample_bytree': 0.8214128717417577, 'max_depth': 4, 'n_estimators': 2215}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.8964317790871545
R2_score :  0.6161606793703946

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:07:28,670] Trial 14 finished with value: 4.822415342725868 and parameters: {'learning_rate': 0.04094568027395599, 'reg_lambda': 0.062232081534995216, 'reg_alpha': 2.1835796233173826e-05, 'subsample': 0.7548016187822557, 'colsample_bytree': 0.9876338614755396, 'max_depth': 5, 'n_estimators': 663}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.822415342725868
R2_score :  0.6522874519661634

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:10:52,191] Trial 15 finished with value: 4.931632162857391 and parameters: {'learning_rate': 0.0776307037492587, 'reg_lambda': 4.849245682816249e-06, 'reg_alpha': 0.20238574029532697, 'subsample': 0.8807157111762105, 'colsample_bytree': 0.4394858138331028, 'max_depth': 4, 'n_estimators': 2124}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.931632162857391
R2_score :  0.7190859172954589

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:13:29,048] Trial 16 finished with value: 5.063364859133622 and parameters: {'learning_rate': 0.09819158855403236, 'reg_lambda': 0.00034341496474826554, 'reg_alpha': 8.685371232187952e-05, 'subsample': 0.6763872875166711, 'colsample_bytree': 0.4762805141338949, 'max_depth': 6, 'n_estimators': 1180}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.063364859133622
R2_score :  0.7137483657870682

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:14:00,344] Trial 17 finished with value: 5.830158951581806 and parameters: {'learning_rate': 0.016688006508771308, 'reg_lambda': 6.846872680092222e-07, 'reg_alpha': 7.811267017168039e-06, 'subsample': 0.9073801101619346, 'colsample_bytree': 0.2137514578792299, 'max_depth': 4, 'n_estimators': 591}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.830158951581806
R2_score :  0.7534792072791402

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-28 21:17:11,041] Trial 18 finished with value: 4.697925384982993 and parameters: {'learning_rate': 0.041172998421319336, 'reg_lambda': 0.2246398383128713, 'reg_alpha': 6.782115019621906e-07, 'subsample': 0.3642868226790396, 'colsample_bytree': 0.3700396266689391, 'max_depth': 5, 'n_estimators': 1931}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.697925384982993
R2_score :  0.7522455232994153

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:18:29,975] Trial 19 finished with value: 4.98551796727635 and parameters: {'learning_rate': 0.0559156637451384, 'reg_lambda': 4.134558762817977e-05, 'reg_alpha': 3.626373817173261e-05, 'subsample': 0.6563325330397529, 'colsample_bytree': 0.6707737713717916, 'max_depth': 6, 'n_estimators': 2539}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.98551796727635
R2_score :  0.6724445628913924

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:20:59,067] Trial 20 finished with value: 5.625785244983675 and parameters: {'learning_rate': 0.0021799216433986378, 'reg_lambda': 0.0006548952573343785, 'reg_alpha': 1.1659993940803949e-08, 'subsample': 0.8183645303365207, 'colsample_bytree': 0.48306887793246134, 'max_depth': 3, 'n_estimators': 1302}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  5.625785244983675
R2_score :  0.7277754723430012

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:23:44,208] Trial 21 finished with value: 4.414182957581479 and parameters: {'learning_rate': 0.029723386540009406, 'reg_lambda': 4.5635006789963095e-05, 'reg_alpha': 57.324263689718975, 'subsample': 0.6521685229298144, 'colsample_bytree': 0.5415459716195707, 'max_depth': 5, 'n_estimators': 1530}. Best is trial 1 with value: 4.37555884175738.

Mean Absolute Error :  4.414182957581479
R2_score :  0.7295748556805105

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:24:34,616] Trial 22 finished with value: 4.16206846602308 and parameters: {'learning_rate': 0.030899569144436076, 'reg_lambda': 5.602972645831192e-05, 'reg_alpha': 36.071524272788935, 'subsample': 0.6530854963857263, 'colsample_bytree': 0.4995139480338302, 'max_depth': 5, 'n_estimators': 585}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.16206846602308
R2_score :  0.7524943906343082

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:25:03,607] Trial 23 finished with value: 4.38973422855411 and parameters: {'learning_rate': 0.017163007580703913, 'reg_lambda': 0.0016049584622673757, 'reg_alpha': 5.598771983444693, 'subsample': 0.7553138125327648, 'colsample_bytree': 0.34749782748917635, 'max_depth': 5, 'n_estimators': 393}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.38973422855411
R2_score :  0.7669688466688336

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:25:26,466] Trial 24 finished with value: 4.452039583893925 and parameters: {'learning_rate': 0.03509657806928665, 'reg_lambda': 0.0009257683647484289, 'reg_alpha': 3.5202753065987493, 'subsample': 0.7393864112984442, 'colsample_bytree': 0.33617502750522643, 'max_depth': 4, 'n_estimators': 355}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.452039583893925
R2_score :  0.7589972403517342

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:25:29,287] Trial 25 finished with value: 11.022509490011672 and parameters: {'learning_rate': 0.010970652304149533, 'reg_lambda': 0.0051398126041990455, 'reg_alpha': 3.526588185877139, 'subsample': 0.6270438848786655, 'colsample_bytree': 0.23955194360159904, 'max_depth': 5, 'n_estimators': 35}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  11.022509490011672
R2_score :  0.12806585527071734

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:26:34,999] Trial 26 finished with value: 4.370567402891388 and parameters: {'learning_rate': 0.02699229892641566, 'reg_lambda': 0.00016100356387594708, 'reg_alpha': 11.879967461336992, 'subsample': 0.7158436554054788, 'colsample_bytree': 0.3801427786438073, 'max_depth': 6, 'n_estimators': 668}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.370567402891388
R2_score :  0.7590264123876233

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:28:01,032] Trial 27 finished with value: 4.386246209050042 and parameters: {'learning_rate': 0.026550288093056526, 'reg_lambda': 0.00021019593476522382, 'reg_alpha': 30.75457392537315, 'subsample': 0.6964318965838936, 'colsample_bytree': 0.39584776073201683, 'max_depth': 6, 'n_estimators': 797}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.386246209050042
R2_score :  0.7593866114558462

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:29:12,606] Trial 28 finished with value: 4.409622182285922 and parameters: {'learning_rate': 0.03913916647192389, 'reg_lambda': 6.844263241858075e-06, 'reg_alpha': 0.2564504982036819, 'subsample': 0.6161134313129298, 'colsample_bytree': 0.4999867077318635, 'max_depth': 6, 'n_estimators': 485}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.409622182285922
R2_score :  0.7398960823438403

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:29:44,094] Trial 29 finished with value: 5.452584033303764 and parameters: {'learning_rate': 0.047418805026620575, 'reg_lambda': 0.06741119800221529, 'reg_alpha': 15.307158610539174, 'subsample': 0.48505318634446026, 'colsample_bytree': 0.28656194863005585, 'max_depth': 6, 'n_estimators': 244}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  5.452584033303764
R2_score :  0.758917240880584

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:30:49,041] Trial 30 finished with value: 4.66906052827371 and parameters: {'learning_rate': 0.03302518646850048, 'reg_lambda': 0.00023026454461969335, 'reg_alpha': 1.412580595281687, 'subsample': 0.44361583014676687, 'colsample_bytree': 0.41351119007989745, 'max_depth': 3, 'n_estimators': 935}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.66906052827371
R2_score :  0.752124758861517

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:32:09,933] Trial 31 finished with value: 4.555563514582846 and parameters: {'learning_rate': 0.027658043703990165, 'reg_lambda': 0.00010758856671957315, 'reg_alpha': 22.275398701418908, 'subsample': 0.6946228704740551, 'colsample_bytree': 0.3940359931873895, 'max_depth': 6, 'n_estimators': 722}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.555563514582846
R2_score :  0.754623380046116

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:33:31,777] Trial 32 finished with value: 4.34299317114551 and parameters: {'learning_rate': 0.026797594821316894, 'reg_lambda': 0.0002564060457360141, 'reg_alpha': 76.6949820877262, 'subsample': 0.6145906762669788, 'colsample_bytree': 0.47278256406827796, 'max_depth': 6, 'n_estimators': 837}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.34299317114551
R2_score :  0.750086223066412

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:33:51,294] Trial 33 finished with value: 4.4858745930537225 and parameters: {'learning_rate': 0.0227581571982003, 'reg_lambda': 0.0018599694533991693, 'reg_alpha': 89.06895052512989, 'subsample': 0.6133987814833736, 'colsample_bytree': 0.4886165366130381, 'max_depth': 6, 'n_estimators': 202}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.4858745930537225
R2_score :  0.7551726813447495

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:35:01,726] Trial 34 finished with value: 5.299714149304696 and parameters: {'learning_rate': 0.036987963179830476, 'reg_lambda': 0.00046469390861853264, 'reg_alpha': 18.42646399212349, 'subsample': 0.571630535200394, 'colsample_bytree': 0.1661875440456722, 'max_depth': 6, 'n_estimators': 1028}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  5.299714149304696
R2_score :  0.7599823692970771

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:36:13,044] Trial 35 finished with value: 4.914944675185423 and parameters: {'learning_rate': 0.030790242788511314, 'reg_lambda': 1.748077456336655e-05, 'reg_alpha': 94.1946482090506, 'subsample': 0.7920290059179739, 'colsample_bytree': 0.32019024682464825, 'max_depth': 3, 'n_estimators': 1362}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.914944675185423
R2_score :  0.7623985806248748

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:37:09,942] Trial 36 finished with value: 4.80031801964555 and parameters: {'learning_rate': 0.07292816644426295, 'reg_lambda': 8.170996853619417e-05, 'reg_alpha': 6.3863989063216104, 'subsample': 0.6715318454096648, 'colsample_bytree': 0.601366615561174, 'max_depth': 6, 'n_estimators': 529}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.80031801964555
R2_score :  0.6866329071328003

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:38:21,024] Trial 37 finished with value: 4.996640815685249 and parameters: {'learning_rate': 0.09203017753952292, 'reg_lambda': 1.7136449551526287e-06, 'reg_alpha': 0.9388516345293361, 'subsample': 0.5404965329688156, 'colsample_bytree': 0.5224150983303405, 'max_depth': 5, 'n_estimators': 806}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.996640815685249
R2_score :  0.686964514892371

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:38:46,757] Trial 38 finished with value: 4.3541906510846005 and parameters: {'learning_rate': 0.0862157449837759, 'reg_lambda': 3.081623986935537e-05, 'reg_alpha': 12.427626587452988, 'subsample': 0.717426360651229, 'colsample_bytree': 0.4522452025645343, 'max_depth': 6, 'n_estimators': 246}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.3541906510846005
R2_score :  0.7445050394158561

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:39:20,848] Trial 39 finished with value: 5.137115658577089 and parameters: {'learning_rate': 0.08491702354015329, 'reg_lambda': 1.4690069071035517e-05, 'reg_alpha': 11.920251518394666, 'subsample': 0.7043986189044606, 'colsample_bytree': 0.27533252184161994, 'max_depth': 6, 'n_estimators': 386}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  5.137115658577089
R2_score :  0.7568061878488215

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:40:27,587] Trial 40 finished with value: 4.430424568482242 and parameters: {'learning_rate': 0.03326878085752285, 'reg_lambda': 3.081192224336148e-05, 'reg_alpha': 1.7356309032739714, 'subsample': 0.7847519525624512, 'colsample_bytree': 0.45673273018484306, 'max_depth': 6, 'n_estimators': 674}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.430424568482242
R2_score :  0.7424285649713435

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:40:46,092] Trial 41 finished with value: 4.265181703833172 and parameters: {'learning_rate': 0.09006283209368009, 'reg_lambda': 9.321571484808277e-05, 'reg_alpha': 31.371323061753866, 'subsample': 0.6184949306956964, 'colsample_bytree': 0.5159777594625803, 'max_depth': 6, 'n_estimators': 195}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.265181703833172
R2_score :  0.7335369705901376

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:40:58,061] Trial 42 finished with value: 4.354079127982873 and parameters: {'learning_rate': 0.0865147497506379, 'reg_lambda': 0.00010394892406704635, 'reg_alpha': 39.650541964801434, 'subsample': 0.5932648985888622, 'colsample_bytree': 0.4426836840816764, 'max_depth': 6, 'n_estimators': 137}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.354079127982873
R2_score :  0.7511735657051752

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:41:08,756] Trial 43 finished with value: 4.3083706432649675 and parameters: {'learning_rate': 0.08771586432379344, 'reg_lambda': 7.052150522155923e-05, 'reg_alpha': 29.570415043362704, 'subsample': 0.5744740784166902, 'colsample_bytree': 0.51244913218334, 'max_depth': 6, 'n_estimators': 117}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.3083706432649675
R2_score :  0.738745116602817

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:41:21,380] Trial 44 finished with value: 4.274497647648274 and parameters: {'learning_rate': 0.08168787891264208, 'reg_lambda': 0.00012961646073970544, 'reg_alpha': 36.810909382562116, 'subsample': 0.5908565765915298, 'colsample_bytree': 0.548903554846571, 'max_depth': 6, 'n_estimators': 138}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.274497647648274
R2_score :  0.7378594044683048

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:41:23,883] Trial 45 finished with value: 5.816274106853026 and parameters: {'learning_rate': 0.08065838432965464, 'reg_lambda': 3.142692032505424e-06, 'reg_alpha': 91.18162004176678, 'subsample': 0.5122890221061458, 'colsample_bytree': 0.578828205851809, 'max_depth': 6, 'n_estimators': 22}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  5.816274106853026
R2_score :  0.698224167874806

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:41:54,161] Trial 46 finished with value: 4.40616087264129 and parameters: {'learning_rate': 0.08961856567055707, 'reg_lambda': 1.3442497528121747e-05, 'reg_alpha': 39.16010131426144, 'subsample': 0.5710589047911794, 'colsample_bytree': 0.5407462311860841, 'max_depth': 5, 'n_estimators': 399}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.40616087264129
R2_score :  0.712649442023616

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:42:48,454] Trial 47 finished with value: 4.808260285803529 and parameters: {'learning_rate': 0.09419455924601666, 'reg_lambda': 0.0004282210733403822, 'reg_alpha': 2.4358525883842916, 'subsample': 0.6402855736737838, 'colsample_bytree': 0.5140981034807655, 'max_depth': 6, 'n_estimators': 521}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.808260285803529
R2_score :  0.7060323865364072

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:43:02,188] Trial 48 finished with value: 4.574980276997106 and parameters: {'learning_rate': 0.09856168657460923, 'reg_lambda': 6.554396515004641e-05, 'reg_alpha': 0.8901672790915536, 'subsample': 0.5862663826543902, 'colsample_bytree': 0.6365253899645124, 'max_depth': 5, 'n_estimators': 158}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.574980276997106
R2_score :  0.6795893738667056

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:43:36,151] Trial 49 finished with value: 4.608285965194395 and parameters: {'learning_rate': 0.08080628170643483, 'reg_lambda': 4.879713547842803e-07, 'reg_alpha': 0.33116907261196377, 'subsample': 0.5076610399444756, 'colsample_bytree': 0.5801344109458466, 'max_depth': 6, 'n_estimators': 337}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.608285965194395
R2_score :  0.7028053839908068

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:43:51,209] Trial 50 finished with value: 4.382142151832527 and parameters: {'learning_rate': 0.08953951989549665, 'reg_lambda': 3.0679493383562366e-06, 'reg_alpha': 5.598254553193769, 'subsample': 0.5454781566305231, 'colsample_bytree': 0.5558117398564005, 'max_depth': 6, 'n_estimators': 138}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.382142151832527
R2_score :  0.7293401201117835

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:44:07,551] Trial 51 finished with value: 4.320723346542186 and parameters: {'learning_rate': 0.07217876635566452, 'reg_lambda': 9.938145268331484e-05, 'reg_alpha': 27.32063502793319, 'subsample': 0.6125282834707884, 'colsample_bytree': 0.42853210182187357, 'max_depth': 6, 'n_estimators': 147}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.320723346542186
R2_score :  0.7677741584150275

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:44:44,802] Trial 52 finished with value: 4.322049629897842 and parameters: {'learning_rate': 0.07206493348975067, 'reg_lambda': 0.00016549610518195129, 'reg_alpha': 36.30551298196829, 'subsample': 0.637520161424352, 'colsample_bytree': 0.5031895503289158, 'max_depth': 6, 'n_estimators': 319}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.322049629897842
R2_score :  0.7322908670175112

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:45:10,019] Trial 53 finished with value: 4.298606277181556 and parameters: {'learning_rate': 0.07364154180621085, 'reg_lambda': 9.951333906093892e-05, 'reg_alpha': 32.391712534429786, 'subsample': 0.6525482827897798, 'colsample_bytree': 0.5038705042596235, 'max_depth': 6, 'n_estimators': 267}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.298606277181556
R2_score :  0.7353061547116665

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:45:19,035] Trial 54 finished with value: 4.4538692815233825 and parameters: {'learning_rate': 0.07713435428620194, 'reg_lambda': 2.9215850748934527e-05, 'reg_alpha': 12.361320695254099, 'subsample': 0.6668167588121499, 'colsample_bytree': 0.416951691937145, 'max_depth': 6, 'n_estimators': 105}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.4538692815233825
R2_score :  0.771260576853233

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:45:40,354] Trial 55 finished with value: 4.448015731890351 and parameters: {'learning_rate': 0.08182598128917774, 'reg_lambda': 6.687611975465178e-05, 'reg_alpha': 5.350714066492331, 'subsample': 0.5871622606316635, 'colsample_bytree': 0.5205567513749965, 'max_depth': 6, 'n_estimators': 237}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.448015731890351
R2_score :  0.7301259268573115

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:45:42,483] Trial 56 finished with value: 6.622156958928079 and parameters: {'learning_rate': 0.06946070738815664, 'reg_lambda': 8.735964381424693e-06, 'reg_alpha': 28.4274477414945, 'subsample': 0.5495753407608353, 'colsample_bytree': 0.6193310565916752, 'max_depth': 5, 'n_estimators': 20}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  6.622156958928079
R2_score :  0.6391540693090769

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:46:38,399] Trial 57 finished with value: 4.443443428703982 and parameters: {'learning_rate': 0.06636236857798948, 'reg_lambda': 0.0006815589776174062, 'reg_alpha': 0.5536176939304908, 'subsample': 0.6589886772655184, 'colsample_bytree': 0.5730345182255399, 'max_depth': 6, 'n_estimators': 462}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.443443428703982
R2_score :  0.7179695101266745

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:47:30,159] Trial 58 finished with value: 4.635923459468388 and parameters: {'learning_rate': 0.07759044545599864, 'reg_lambda': 0.0035001045818649807, 'reg_alpha': 0.0915880119794646, 'subsample': 0.6065205704884374, 'colsample_bytree': 0.46516654652772643, 'max_depth': 5, 'n_estimators': 585}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.635923459468388
R2_score :  0.7230579096122622

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:47:56,273] Trial 59 finished with value: 4.643469812510305 and parameters: {'learning_rate': 0.08264363152171751, 'reg_lambda': 0.0007966036792914367, 'reg_alpha': 2.4060397534826166, 'subsample': 0.5195695991434268, 'colsample_bytree': 0.4270486615478562, 'max_depth': 6, 'n_estimators': 261}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.643469812510305
R2_score :  0.7497860095660704

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:51:10,783] Trial 60 finished with value: 4.497823732625809 and parameters: {'learning_rate': 0.062402195410235915, 'reg_lambda': 7.151970795658751e-05, 'reg_alpha': 41.372774816790105, 'subsample': 0.6772116561208983, 'colsample_bytree': 0.6732227646731582, 'max_depth': 6, 'n_estimators': 1782}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.497823732625809
R2_score :  0.6931391611806134

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:51:37,794] Trial 61 finished with value: 4.273382612810257 and parameters: {'learning_rate': 0.07348002617117197, 'reg_lambda': 0.00015649057066246857, 'reg_alpha': 32.34496171947777, 'subsample': 0.6299800502212085, 'colsample_bytree': 0.5004074588295053, 'max_depth': 6, 'n_estimators': 298}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.273382612810257
R2_score :  0.7130715305702116

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:51:49,354] Trial 62 finished with value: 4.2632241002943445 and parameters: {'learning_rate': 0.07523083382832856, 'reg_lambda': 0.0002509195927318387, 'reg_alpha': 8.078226277390751, 'subsample': 0.6288097577757339, 'colsample_bytree': 0.5253791695278762, 'max_depth': 6, 'n_estimators': 124}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.2632241002943445
R2_score :  0.7326839584494931

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:52:39,184] Trial 63 finished with value: 4.547632667369512 and parameters: {'learning_rate': 0.0762258231355543, 'reg_lambda': 0.000340741999037839, 'reg_alpha': 7.121707433651155, 'subsample': 0.6456641151812221, 'colsample_bytree': 0.524512656644265, 'max_depth': 6, 'n_estimators': 421}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.547632667369512
R2_score :  0.7238210165339498

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:53:15,057] Trial 64 finished with value: 4.448519823047109 and parameters: {'learning_rate': 0.08027689241948374, 'reg_lambda': 0.0017809449955525874, 'reg_alpha': 9.512855552006748, 'subsample': 0.5639793771436592, 'colsample_bytree': 0.49158663571069644, 'max_depth': 6, 'n_estimators': 303}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.448519823047109
R2_score :  0.7328386718224194

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:53:49,922] Trial 65 finished with value: 4.331125732778508 and parameters: {'learning_rate': 0.08438462575444312, 'reg_lambda': 0.00017816963665836125, 'reg_alpha': 4.02396355583523, 'subsample': 0.7381117761903162, 'colsample_bytree': 0.5552328563762057, 'max_depth': 4, 'n_estimators': 559}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.331125732778508
R2_score :  0.7022662882998613

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:54:00,700] Trial 66 finished with value: 4.254392855450327 and parameters: {'learning_rate': 0.07555500224775527, 'reg_lambda': 2.309574248681351e-05, 'reg_alpha': 99.91990480265024, 'subsample': 0.6903191881378571, 'colsample_bytree': 0.594115371295488, 'max_depth': 6, 'n_estimators': 104}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.254392855450327
R2_score :  0.7323209321883501

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:54:28,843] Trial 67 finished with value: 4.579813424204215 and parameters: {'learning_rate': 0.07390438155253846, 'reg_lambda': 2.52701259438616e-05, 'reg_alpha': 56.59172936958021, 'subsample': 0.6866183726025779, 'colsample_bytree': 0.5987200755472759, 'max_depth': 6, 'n_estimators': 286}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.579813424204215
R2_score :  0.7197361484540286

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:54:48,711] Trial 68 finished with value: 4.196502887233966 and parameters: {'learning_rate': 0.07001527123734705, 'reg_lambda': 0.00038791894306115473, 'reg_alpha': 98.95371012330142, 'subsample': 0.628179169509355, 'colsample_bytree': 0.5462755630113153, 'max_depth': 6, 'n_estimators': 215}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.196502887233966
R2_score :  0.7258173367482088

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:55:29,190] Trial 69 finished with value: 4.334381403229536 and parameters: {'learning_rate': 0.06818252156129706, 'reg_lambda': 0.0004143393280760942, 'reg_alpha': 87.98017018768107, 'subsample': 0.6322079294312514, 'colsample_bytree': 0.6430902014655004, 'max_depth': 5, 'n_estimators': 438}. Best is trial 22 with value: 4.16206846602308.

Mean Absolute Error :  4.334381403229536
R2_score :  0.7179745159099504

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:55:54,830] Trial 70 finished with value: 4.144307145683879 and parameters: {'learning_rate': 0.060874267198799376, 'reg_lambda': 0.0008196424699002651, 'reg_alpha': 14.698503071138058, 'subsample': 0.7005947696689363, 'colsample_bytree': 0.5442856655981725, 'max_depth': 6, 'n_estimators': 210}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.144307145683879
R2_score :  0.7411635677250943

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:56:05,345] Trial 71 finished with value: 4.216353911262755 and parameters: {'learning_rate': 0.06209686627923121, 'reg_lambda': 0.00108033870884223, 'reg_alpha': 14.425368269472887, 'subsample': 0.7047570169460033, 'colsample_bytree': 0.5430695173707097, 'max_depth': 6, 'n_estimators': 83}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.216353911262755
R2_score :  0.7447629844832471

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:56:14,010] Trial 72 finished with value: 4.442927967867167 and parameters: {'learning_rate': 0.0620082815017137, 'reg_lambda': 0.0012478463538253914, 'reg_alpha': 13.813313670717967, 'subsample': 0.6866226413767275, 'colsample_bytree': 0.5820897713055916, 'max_depth': 6, 'n_estimators': 63}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.442927967867167
R2_score :  0.7496117907131414

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:56:36,924] Trial 73 finished with value: 4.351794957377905 and parameters: {'learning_rate': 0.06142274043378958, 'reg_lambda': 0.0035207884187649723, 'reg_alpha': 17.913302035804644, 'subsample': 0.7196935931580135, 'colsample_bytree': 0.4655435459146039, 'max_depth': 6, 'n_estimators': 202}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.351794957377905
R2_score :  0.7381589943289952

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 15:57:18,136] Trial 74 finished with value: 4.3710426334684955 and parameters: {'learning_rate': 0.06866456407534142, 'reg_lambda': 0.0008568117395720759, 'reg_alpha': 7.755173050362583, 'subsample': 0.7497106171625239, 'colsample_bytree': 0.534105029776069, 'max_depth': 6, 'n_estimators': 347}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.3710426334684955
R2_score :  0.7095465847139789

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 16:02:32,661] Trial 75 finished with value: 5.194821686721342 and parameters: {'learning_rate': 0.058996378860857235, 'reg_lambda': 0.00028986400881725116, 'reg_alpha': 3.6244787525150906, 'subsample': 0.7173318377412843, 'colsample_bytree': 0.6126226603703888, 'max_depth': 6, 'n_estimators': 2960}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  5.194821686721342
R2_score :  0.6597540545776153

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 16:03:36,643] Trial 76 finished with value: 4.379539755331345 and parameters: {'learning_rate': 0.06517790066148384, 'reg_lambda': 0.0005686459283779009, 'reg_alpha': 64.84556852625104, 'subsample': 0.6956691489135968, 'colsample_bytree': 0.47933883777638336, 'max_depth': 6, 'n_estimators': 620}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.379539755331345
R2_score :  0.7394218008012313

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 16:03:53,513] Trial 77 finished with value: 4.32725933895831 and parameters: {'learning_rate': 0.05443444243009719, 'reg_lambda': 3.931702928280631e-05, 'reg_alpha': 20.462047635324122, 'subsample': 0.7647378430226827, 'colsample_bytree': 0.5596644869359695, 'max_depth': 6, 'n_estimators': 190}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.32725933895831
R2_score :  0.7385981763015244

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 16:03:58,736] Trial 78 finished with value: 4.415439169207173 and parameters: {'learning_rate': 0.06659804350711579, 'reg_lambda': 0.011105218071647164, 'reg_alpha': 93.73460808896282, 'subsample': 0.6640237201920987, 'colsample_bytree': 0.541755651027377, 'max_depth': 4, 'n_estimators': 77}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.415439169207173
R2_score :  0.7454738318076641

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[I 2023-04-29 16:07:34,211] Trial 79 finished with value: 4.813531152463998 and parameters: {'learning_rate': 0.07035064337196545, 'reg_lambda': 0.0002147660371873115, 'reg_alpha': 1.614675960285272, 'subsample': 0.627188199496903, 'colsample_bytree': 0.4919196737316733, 'max_depth': 6, 'n_estimators': 2451}. Best is trial 70 with value: 4.144307145683879.

Mean Absolute Error :  4.813531152463998
R2_score :  0.7154486232380166

C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_12852\719259616.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)

In [1]:
"""Uncomment for tuning the model"""
import optuna
def run(trial):
    learning_rate = trial.suggest_float("learning_rate", 1e-3, 0.1)
    reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
    reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
    subsample = trial.suggest_float("subsample", 0.1, 1.0)
    colsample_bytree = trial.suggest_float("colsample_bytree", 0.1, 1.0)
    max_depth = trial.suggest_int("max_depth", 3, 6)
    n_estimators = trial.suggest_int("n_estimators", 20, 3000)


    model = xgb.XGBRegressor(
            random_state=42,
            objective='reg:squarederror',
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            reg_lambda=reg_lambda,
            reg_alpha=reg_alpha,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            max_depth=max_depth,
            eval_metric='r2_score'
        )
    model.fit(X_train, y_train)
    preds_valid = model.predict(X_test)
    mae_ = mean_absolute_error(y_test, preds_valid)
    r2_sc = r2_score(y_test, preds_valid)
    print("Mean Absolute Error : ", mae_)
    print("R2_score : ", r2_sc)
    return r2_sc

study = optuna.create_study(direction="minimize")
study.optimize(run, n_trials=100)

# study.best_params

c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[I 2023-04-30 20:29:28,143] A new study created in memory with name: no-name-479de14e-c7bb-45e0-8584-c0aa19e972fd
C:\Users\nshre\AppData\Local\Temp\ipykernel_15036\4217039969.py:5: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_lambda = trial.suggest_loguniform("reg_lambda", 1e-8, 100.0)
C:\Users\nshre\AppData\Local\Temp\ipykernel_15036\4217039969.py:6: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.
  reg_alpha = trial.suggest_loguniform("reg_alpha", 1e-8, 100.0)
[W 2023-04-30 20:29:28,150] Trial 0 failed with parameters: {'learning_rate': 0.07791084133262398, 'reg_lambda': 0.0007188067232693896, 'reg_alpha': 1.823825918142417e-08, 'subsample': 0.6392031163550392, 'colsample_bytree': 0.8021660748450357, 'max_depth': 5, 'n_estimators': 1277} because of the following error: NameError("name 'xgb' is not defined").
Traceback (most recent call last):
  File "c:\Users\nshre\anaconda3\envs\auto_gpt\lib\site-packages\optuna\study\_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "C:\Users\nshre\AppData\Local\Temp\ipykernel_15036\4217039969.py", line 13, in run
    model = xgb.XGBRegressor(
NameError: name 'xgb' is not defined
[W 2023-04-30 20:29:28,152] Trial 0 failed with value None.

NameError: name 'xgb' is not defined